"use client";

import { useEpewLanguage } from "@/app/components/EpewLanguage";
import { SupportCommitment } from "./types";

interface Props { commitments: SupportCommitment[]; selectedBusiness?: any; }

const copy = {
  en:{ mine:"My Entrepreneurs", empty:"You have not supported an entrepreneur yet. Explore the EPEW Marketplace and choose a qualified entrepreneur to begin your impact journey.", explore:"Explore Marketplace", intro:"View entrepreneurs you selected to support and businesses already connected to your EPEW participation.", ready:"Ready to Support", businessId:"Business ID", selected:"Selected Entrepreneur", selectedBody:"You selected this entrepreneur for support. Review the business and choose your Support Units when you are ready.", support:"Support This Entrepreneur", viewBusiness:"View This Business", founder:"Founder & Entrepreneur", businessStatus:"Business Status", community:"Community Served", opening:"Opening Date", units:"My Units", supporting:"Supporting Information", supportType:"Support Type", contribution:"Contribution", paymentStatus:"Payment Status", impact:"View Impact Details", publicPage:"Public Business Page"},
  ht:{ mine:"Antreprenè Mwen yo", empty:"Ou poko sipòte okenn antreprenè. Eksplore Mache EPEW la epi chwazi yon antreprenè ki kalifye pou kòmanse pakou enpak ou.", explore:"Eksplore Mache a", intro:"Gade antreprenè ou chwazi sipòte yo ak biznis ki deja konekte ak patisipasyon EPEW ou.", ready:"Pare pou Sipò", businessId:"ID Biznis", selected:"Antreprenè Chwazi", selectedBody:"Ou chwazi antreprenè sa a pou sipò. Revize biznis la epi chwazi Inite Sipò ou lè ou pare.", support:"Sipòte Antreprenè Sa a", viewBusiness:"Gade Biznis Sa a", founder:"Fondatè & Antreprenè", businessStatus:"Estati Biznis", community:"Kominote Sèvi", opening:"Dat Ouvèti", units:"Inite Mwen", supporting:"Enfòmasyon Sipò", supportType:"Kalite Sipò", contribution:"Kontribisyon", paymentStatus:"Estati Peman", impact:"Gade Detay Enpak", publicPage:"Paj Piblik Biznis"},
  fr:{ mine:"Mes Entrepreneurs", empty:"Vous n’avez pas encore soutenu d’entrepreneur. Explorez la Place de Marché EPEW et choisissez un entrepreneur qualifié pour commencer votre parcours d’impact.", explore:"Explorer la Place de Marché", intro:"Consultez les entrepreneurs que vous avez choisi de soutenir et les entreprises déjà liées à votre participation EPEW.", ready:"Prêt à Soutenir", businessId:"ID Entreprise", selected:"Entrepreneur Sélectionné", selectedBody:"Vous avez sélectionné cet entrepreneur pour le soutenir. Examinez l’entreprise et choisissez vos Unités de Soutien lorsque vous êtes prêt.", support:"Soutenir Cet Entrepreneur", viewBusiness:"Voir Cette Entreprise", founder:"Fondateur & Entrepreneur", businessStatus:"Statut de l’Entreprise", community:"Communauté Desservie", opening:"Date d’Ouverture", units:"Mes Unités", supporting:"Informations de Soutien", supportType:"Type de Soutien", contribution:"Contribution", paymentStatus:"Statut du Paiement", impact:"Voir les Détails d’Impact", publicPage:"Page Publique de l’Entreprise"},
  es:{ mine:"Mis Emprendedores", empty:"Aún no ha apoyado a ningún emprendedor. Explore el Mercado EPEW y elija un emprendedor calificado para comenzar su recorrido de impacto.", explore:"Explorar el Mercado", intro:"Vea los emprendedores que seleccionó para apoyar y los negocios ya conectados con su participación en EPEW.", ready:"Listo para Apoyar", businessId:"ID del Negocio", selected:"Emprendedor Seleccionado", selectedBody:"Seleccionó a este emprendedor para apoyarlo. Revise el negocio y elija sus Unidades de Apoyo cuando esté listo.", support:"Apoyar a Este Emprendedor", viewBusiness:"Ver Este Negocio", founder:"Fundador y Emprendedor", businessStatus:"Estado del Negocio", community:"Comunidad Atendida", opening:"Fecha de Apertura", units:"Mis Unidades", supporting:"Información de Apoyo", supportType:"Tipo de Apoyo", contribution:"Contribución", paymentStatus:"Estado del Pago", impact:"Ver Detalles del Impacto", publicPage:"Página Pública del Negocio"}
};

export default function EntrepreneurPortfolio({commitments,selectedBusiness}:Props){ const {language}=useEpewLanguage(); const t=copy[language];
  if(commitments.length===0&&!selectedBusiness) return <section className="mb-10"><div className="rounded-3xl bg-white p-10 text-center shadow-2xl"><h2 className="text-5xl font-extrabold text-[#06245c]">{t.mine}</h2><p className="mx-auto mt-5 max-w-4xl text-2xl leading-relaxed text-gray-700">{t.empty}</p><a href="/supporters/marketplace" className="mt-8 inline-block rounded-2xl bg-[#06245c] px-10 py-5 text-2xl font-black text-white hover:bg-green-700">{t.explore}</a></div></section>;
  return <section className="mb-10"><div className="rounded-3xl bg-white p-10 shadow-2xl"><h2 className="text-5xl font-extrabold text-[#06245c]">{t.mine}</h2><p className="mt-4 text-2xl leading-relaxed text-gray-700">{t.intro}</p><div className="mt-10 grid gap-8 xl:grid-cols-2">{selectedBusiness?<SelectedBusinessCard business={selectedBusiness} t={t}/>:null}{commitments.map(item=><PortfolioCard key={item.id} item={item} t={t}/>)}</div></div></section>;
}

function SelectedBusinessCard({business,t}:{business:any;t:any}){ const businessId=business.public_business_id||""; const businessName=business.business_name||"Business"; const entrepreneurName=business.full_name||"EPEW Entrepreneur"; const entrepreneurPhoto=business.entrepreneur_photo||business.entrepreneur_photo_url||business.photo_url||""; const businessLogo=business.business_logo||business.business_logo_url||business.logo_url||""; return <div className="rounded-3xl border-2 border-green-300 bg-green-50 p-8 shadow-lg"><div className="mb-6 inline-flex rounded-full bg-green-700 px-5 py-2 text-sm font-black uppercase tracking-wider text-white">{t.ready}</div><div className="flex flex-col gap-6 md:flex-row md:items-center"><div className="flex h-32 w-32 items-center justify-center overflow-hidden rounded-3xl bg-[#06245c] text-6xl text-white shadow-lg">{entrepreneurPhoto?<img src={entrepreneurPhoto} alt={entrepreneurName} className="h-full w-full object-cover"/>:"👤"}</div><div className="flex h-32 w-32 items-center justify-center overflow-hidden rounded-3xl bg-white text-6xl shadow-lg">{businessLogo?<img src={businessLogo} alt={businessName} className="h-full w-full object-contain p-3"/>:"🏢"}</div><div className="flex-1"><h3 className="text-4xl font-black text-[#06245c]">{businessName}</h3><p className="mt-2 text-xl font-black text-green-700">{t.businessId}: {businessId}</p><p className="mt-2 text-2xl text-gray-700">{entrepreneurName}</p><p className="mt-1 text-lg font-bold uppercase tracking-wide text-gray-500">{t.selected}</p></div></div><div className="mt-8 rounded-2xl bg-white p-5"><p className="text-lg leading-relaxed text-gray-700">{t.selectedBody}</p></div><div className="mt-8 flex flex-wrap gap-4"><a href={`/support/${businessId}/checkout`} className="rounded-2xl bg-green-700 px-8 py-4 text-xl font-black text-white hover:bg-[#06245c]">{t.support}</a><a href={`/business/${businessId}`} className="rounded-2xl border-2 border-[#06245c] px-8 py-4 text-xl font-black text-[#06245c] hover:bg-[#06245c] hover:text-white">{t.viewBusiness}</a></div></div> }

function PortfolioCard({item,t}:{item:SupportCommitment;t:any}){ const businessId=item.public_business_id||item.entrepreneur_id||"Business ID Pending"; const businessName=item.business_name||"Business Name Pending"; const entrepreneurName=item.entrepreneur_name||"Entrepreneur Pending"; const openingDate=item.business_opening_date?new Date(item.business_opening_date).toLocaleDateString():"Pending Annual Meeting Schedule"; return <div className="rounded-3xl border border-gray-200 bg-[#f5f7fb] p-8 shadow-lg"><div className="flex flex-col gap-6 md:flex-row md:items-center"><div className="flex h-32 w-32 items-center justify-center overflow-hidden rounded-3xl bg-[#06245c] text-6xl text-white shadow-lg">{item.entrepreneur_photo_url?<img src={item.entrepreneur_photo_url} alt={entrepreneurName} className="h-full w-full object-cover"/>:"👤"}</div><div className="flex h-32 w-32 items-center justify-center overflow-hidden rounded-3xl bg-white text-6xl shadow-lg">{item.business_logo_url?<img src={item.business_logo_url} alt={businessName} className="h-full w-full object-contain p-4"/>:"🏢"}</div><div className="flex-1"><h3 className="text-4xl font-black text-[#06245c]">{businessName}</h3><p className="mt-2 text-xl font-black text-green-700">{t.businessId}: {businessId}</p><p className="mt-2 text-2xl text-gray-700">{entrepreneurName}</p><p className="mt-1 text-lg font-bold uppercase tracking-wide text-gray-500">{t.founder}</p></div></div><div className="mt-8 grid gap-5 md:grid-cols-2"><InfoBox label={t.businessStatus} value={item.business_status||"In Development"}/><InfoBox label={t.community} value={item.community||item.country||"Community Pending"}/><InfoBox label={t.opening} value={openingDate}/><InfoBox label={t.units} value={`${item.units||0}`}/></div><div className="mt-8 rounded-3xl bg-white p-6"><h4 className="text-2xl font-extrabold text-[#06245c]">{t.supporting}</h4><div className="mt-4 grid gap-4 md:grid-cols-3"><MiniInfo label={t.supportType} value={item.support_type||"Pending"}/><MiniInfo label={t.contribution} value={`$${Number(item.amount||0).toLocaleString()}`}/><MiniInfo label={t.paymentStatus} value={item.payment_status||"Pending"}/></div></div><div className="mt-8 flex flex-wrap gap-4"><a href={`/supporters/businesses/${businessId}`} className="rounded-2xl bg-[#06245c] px-8 py-4 text-xl font-black text-white hover:bg-green-700">{t.impact}</a><a href={`/business/${businessId}`} className="rounded-2xl border-2 border-[#06245c] px-8 py-4 text-xl font-black text-[#06245c] hover:bg-[#06245c] hover:text-white">{t.publicPage}</a></div></div> }
function InfoBox({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm font-black uppercase tracking-wide text-gray-500">{label}</p><p className="mt-2 text-xl font-extrabold text-[#06245c]">{value}</p></div>}
function MiniInfo({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-[#f5f7fb] p-4"><p className="text-sm font-bold text-gray-500">{label}</p><p className="mt-2 text-lg font-black text-[#06245c]">{value}</p></div>}
