/**
 * ============================================================
 * EPEW-EDE-IBOS
 * Enterprise Translation Center
 * ------------------------------------------------------------
 * Safe Code Transformer
 * Version: 1.0.0
 * ============================================================
 *
 * PURPOSE
 * -------
 * Converts approved hardcoded user-facing text findings into:
 *
 * 1. English master namespace entries
 * 2. HT / FR / ES namespace structures
 * 3. Safe source-code transformation plans
 * 4. Backups before source modification
 * 5. Review records for unsafe transformations
 *
 * IMPORTANT
 * ---------
 * This transformer is conservative by design.
 *
 * It automatically transforms only findings that can be located
 * unambiguously and whose syntax can be replaced safely.
 *
 * Dynamic expressions, uncertain matches, server-only files,
 * API responses, object messages, and template literals are sent
 * to review instead of being modified automatically.
 */

import fs from "node:fs/promises";
import path from "node:path";

import type {
  TranslationBuildResult,
  TranslationLanguage,
} from "./types";

import type {
  HardcodedTextKind,
  HardcodedTextOccurrence,
  ProjectHardcodedTextAnalysis,
} from "./source-intelligence/hardcoded-text-detector";

import {
  createStableId,
  formatJson,
  normalizePath,
  nowIso,
  safeParseJson,
  uniqueValues,
} from "./utils";

/**
 * Transformer version.
 */
export const IBOS_SAFE_CODE_TRANSFORMER_VERSION = "1.0.0";

/**
 * Languages generated by the transformer.
 */
type TargetTranslationLanguage = Exclude<
  TranslationLanguage,
  "en"
>;

const TARGET_LANGUAGES: readonly TargetTranslationLanguage[] = [
  "ht",
  "fr",
  "es",
];

/**
 * Findings that may be safely transformed automatically.
 */
const DEFAULT_AUTOMATIC_KINDS = new Set<HardcodedTextKind>([
  "jsx_text",
  "jsx_attribute",
]);

/**
 * Files that may contain source code transformed by this engine.
 */
const SUPPORTED_SOURCE_EXTENSIONS = new Set([
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
]);

/**
 * Status of one proposed source transformation.
 */
export type SourceTransformationStatus =
  | "planned"
  | "applied"
  | "skipped"
  | "review_required"
  | "failed";

/**
 * Reason a transformation requires review.
 */
export type TransformationReviewReason =
  | "missing_namespace"
  | "unsupported_kind"
  | "low_confidence"
  | "source_file_missing"
  | "source_match_missing"
  | "ambiguous_source_match"
  | "unsupported_source_file"
  | "translation_runtime_missing"
  | "server_component"
  | "dynamic_expression"
  | "syntax_validation_failed"
  | "write_failed";

/**
 * One source-code replacement.
 */
export interface SourceTextReplacement {
  id: string;

  sourceFile: string;
  namespace: string;

  occurrenceId: string;
  kind: HardcodedTextKind;

  key: string;
  fullKey: string;
  masterValue: string;

  originalText: string;
  originalExpression: string;
  replacementExpression: string;

  startIndex: number;
  endIndex: number;

  line: number;
  column: number;

  confidence: number;
}

/**
 * Complete transformation plan for one source file.
 */
export interface SourceFileTransformationPlan {
  id: string;

  sourceFile: string;
  absolutePath: string;

  namespace: string | null;

  originalSource: string;
  transformedSource: string;

  replacements: SourceTextReplacement[];

  requiresTranslationRuntime: boolean;
  translationRuntimePresent: boolean;
  translationRuntimeInjected: boolean;

  status: SourceTransformationStatus;

  reviewReasons: TransformationReviewReason[];
  warnings: string[];
  errors: string[];
}

/**
 * One record requiring review.
 */
export interface TransformationReviewItem {
  id: string;

  occurrenceId: string;
  sourceFile: string;
  route: string | null;
  namespace: string | null;

  text: string;
  kind: HardcodedTextKind;

  line: number;
  column: number;
  confidence: number;

  reason: TransformationReviewReason;
  explanation: string;

  suggestedKey: string;
  suggestedReplacement: string;

  createdAt: string;
}

/**
 * Namespace entries generated from source findings.
 */
export interface GeneratedNamespaceEntry {
  namespace: string;
  key: string;
  value: string;
  occurrenceIds: string[];
}

/**
 * Result of namespace generation.
 */
export interface NamespaceGenerationResult {
  generatedFiles: string[];
  updatedFiles: string[];
  unchangedFiles: string[];

  namespacesCreated: string[];
  namespacesUpdated: string[];

  keysCreated: number;
  keysPreserved: number;

  errors: string[];
}

/**
 * Optional linguistic translation provider.
 *
 * The EPEW Translation Agent can be connected here.
 */
export type EnterpriseTranslationProvider = (input: {
  sourceLanguage: "en";
  targetLanguage: Exclude<TranslationLanguage, "en">;

  namespace: string;
  key: string;
  sourceText: string;
}) => Promise<string>;

/**
 * Safe Code Transformer configuration.
 */
export interface SafeCodeTransformerOptions {
  projectRoot?: string;

  /**
   * Root folder containing language namespace folders.
   */
  messagesRoot?: string;

  /**
   * Apply changes to source files.
   *
   * When false, the transformer generates preview plans only.
   */
  applyChanges?: boolean;

  /**
   * Generate English master namespace files.
   */
  generateEnglishNamespaces?: boolean;

  /**
   * Generate HT / FR / ES namespace files.
   */
  generateTargetNamespaces?: boolean;

  /**
   * Preserve existing translated values.
   */
  preserveExistingTranslations?: boolean;

  /**
   * Create source-file backups before applying changes.
   */
  createBackups?: boolean;

  /**
   * Backup root.
   */
  backupRoot?: string;

  /**
   * Minimum confidence for automatic transformation.
   */
  minimumAutomaticConfidence?: number;

  /**
   * Automatically inject the translation hook when possible.
   */
  injectTranslationRuntime?: boolean;

  /**
   * Translation hook import.
   */
  translationHookImport?: string;

  /**
   * Translation hook name.
   */
  translationHookName?: string;

  /**
   * Translation function variable.
   */
  translationFunctionName?: string;

  /**
   * Optional enterprise translation provider.
   *
   * Without this provider, generated target-language values use
   * the English source text as a safe fallback.
   */
  translationProvider?: EnterpriseTranslationProvider;

  /**
   * Restrict processing to specific source files.
   */
  includeFiles?: string[];

  /**
   * Skip files matching these patterns.
   */
  excludeFilePatterns?: RegExp[];

  /**
   * Maximum number of files modified in one execution.
   */
  maximumFilesToModify?: number;
}

/**
 * Complete transformer output.
 */
export interface SafeCodeTransformerResult {
  success: boolean;

  transformationId: string;
  platform: "EPEW-EDE-IBOS";
  engine: "SAFE_CODE_TRANSFORMER";
  version: string;

  startedAt: string;
  completedAt: string;
  durationMs: number;

  mode: "preview" | "apply";

  analyzedOccurrences: number;
  automaticallyPlannedOccurrences: number;
  appliedOccurrences: number;
  reviewRequiredOccurrences: number;

  filePlans: SourceFileTransformationPlan[];
  reviewQueue: TransformationReviewItem[];

  namespaceGeneration: NamespaceGenerationResult;

  backupFiles: string[];

  generatedFiles: string[];
  updatedFiles: string[];
  skippedFiles: string[];

  errors: string[];

  buildResult: TranslationBuildResult;
}

/**
 * Default transformer behavior.
 */
const DEFAULT_OPTIONS: Required<
  Pick<
    SafeCodeTransformerOptions,
    | "messagesRoot"
    | "applyChanges"
    | "generateEnglishNamespaces"
    | "generateTargetNamespaces"
    | "preserveExistingTranslations"
    | "createBackups"
    | "backupRoot"
    | "minimumAutomaticConfidence"
    | "injectTranslationRuntime"
    | "translationHookImport"
    | "translationHookName"
    | "translationFunctionName"
    | "maximumFilesToModify"
  >
> = {
  messagesRoot: "app/messages",

  applyChanges: false,

  generateEnglishNamespaces: true,
  generateTargetNamespaces: true,

  preserveExistingTranslations: true,

  createBackups: true,

  backupRoot:
    "data/enterprise/ibos/translation-center/backups/source",

  minimumAutomaticConfidence: 0.95,

  injectTranslationRuntime: true,

  translationHookImport:
  "@/app/components/enterprise/language",

translationHookName: "useTranslation",

translationFunctionName: "t",

  maximumFilesToModify: 500,
};

/**
 * Returns whether a path exists.
 */
async function pathExists(targetPath: string): Promise<boolean> {
  try {
    await fs.access(targetPath);
    return true;
  } catch {
    return false;
  }
}

/**
 * Creates a directory recursively.
 */
async function ensureDirectory(
  directoryPath: string,
): Promise<void> {
  await fs.mkdir(directoryPath, {
    recursive: true,
  });
}

/**
 * Returns a project-relative normalized path.
 */
function toProjectRelativePath(
  projectRoot: string,
  absolutePath: string,
): string {
  return normalizePath(
    path.relative(projectRoot, absolutePath),
  );
}

/**
 * Converts a dotted key into nested JSON.
 */
function setNestedValue(
  target: Record<string, unknown>,
  dottedKey: string,
  value: string,
  preserveExisting: boolean,
): {
  created: boolean;
  preserved: boolean;
} {
  const segments = dottedKey
    .split(".")
    .map((segment) => segment.trim())
    .filter(Boolean);

  if (segments.length === 0) {
    return {
      created: false,
      preserved: false,
    };
  }

  let current = target;

  for (
    let index = 0;
    index < segments.length - 1;
    index += 1
  ) {
    const segment = segments[index];

    if (!segment) {
      continue;
    }

    const existing = current[segment];

    if (
      !existing ||
      typeof existing !== "object" ||
      Array.isArray(existing)
    ) {
      current[segment] = {};
    }

    current = current[segment] as Record<string, unknown>;
  }

  const finalSegment = segments.at(-1);

  if (!finalSegment) {
    return {
      created: false,
      preserved: false,
    };
  }

  if (
    preserveExisting &&
    current[finalSegment] !== undefined
  ) {
    return {
      created: false,
      preserved: true,
    };
  }

  const created = current[finalSegment] === undefined;

  current[finalSegment] = value;

  return {
    created,
    preserved: false,
  };
}

/**
 * Returns a nested JSON value.
 */
function getNestedValue(
  target: Record<string, unknown>,
  dottedKey: string,
): unknown {
  const segments = dottedKey
    .split(".")
    .map((segment) => segment.trim())
    .filter(Boolean);

  let current: unknown = target;

  for (const segment of segments) {
    if (
      !current ||
      typeof current !== "object" ||
      Array.isArray(current)
    ) {
      return undefined;
    }

    current = (
      current as Record<string, unknown>
    )[segment];
  }

  return current;
}

/**
 * Reads a JSON object or returns an empty object.
 */
async function readJsonObject(
  filePath: string,
): Promise<{
  data: Record<string, unknown>;
  exists: boolean;
  error: string | null;
}> {
  if (!(await pathExists(filePath))) {
    return {
      data: {},
      exists: false,
      error: null,
    };
  }

  try {
    const content = await fs.readFile(filePath, "utf8");

    const parsed =
      safeParseJson<Record<string, unknown>>(content);

    if (!parsed.success) {
      return {
        data: {},
        exists: true,
        error: parsed.error,
      };
    }

    return {
      data: parsed.data,
      exists: true,
      error: null,
    };
  } catch (error) {
    return {
      data: {},
      exists: true,
      error:
        error instanceof Error
          ? error.message
          : "Unknown JSON-reading error.",
    };
  }
}

/**
 * Writes one JSON file.
 */
async function writeJsonObject(
  filePath: string,
  value: Record<string, unknown>,
): Promise<void> {
  await ensureDirectory(path.dirname(filePath));

  await fs.writeFile(
    filePath,
    formatJson(value, 2),
    "utf8",
  );
}

/**
 * Creates one review item.
 */
function createReviewItem(input: {
  occurrence: HardcodedTextOccurrence;
  reason: TransformationReviewReason;
  explanation: string;
}): TransformationReviewItem {
  return {
    id: createStableId(
      "translation-transformation-review",
      input.occurrence.id,
      input.reason,
    ),

    occurrenceId: input.occurrence.id,
    sourceFile: input.occurrence.sourceFile,
    route: input.occurrence.route,
    namespace:
      input.occurrence.suggestedNamespace ??
      input.occurrence.namespace,

    text: input.occurrence.text,
    kind: input.occurrence.kind,

    line: input.occurrence.line,
    column: input.occurrence.column,
    confidence: input.occurrence.confidence,

    reason: input.reason,
    explanation: input.explanation,

    suggestedKey: input.occurrence.suggestedKey,
    suggestedReplacement:
      input.occurrence.suggestedReplacement,

    createdAt: nowIso(),
  };
}

/**
 * Determines whether a source file is supported.
 */
function isSupportedSourceFile(
  sourceFile: string,
): boolean {
  return SUPPORTED_SOURCE_EXTENSIONS.has(
    path.extname(sourceFile).toLowerCase(),
  );
}

/**
 * Determines whether an occurrence is eligible for automatic work.
 */
function getAutomaticEligibility(input: {
  occurrence: HardcodedTextOccurrence;
  options: typeof DEFAULT_OPTIONS &
    SafeCodeTransformerOptions;
}):
  | {
      eligible: true;
    }
  | {
      eligible: false;
      reason: TransformationReviewReason;
      explanation: string;
    } {
  const occurrence = input.occurrence;

  const namespace =
    occurrence.suggestedNamespace ??
    occurrence.namespace;

  if (!namespace) {
    return {
      eligible: false,
      reason: "missing_namespace",
      explanation:
        "The finding has no registered translation namespace.",
    };
  }

  if (!isSupportedSourceFile(occurrence.sourceFile)) {
    return {
      eligible: false,
      reason: "unsupported_source_file",
      explanation:
        "The source file extension is not supported by the Safe Code Transformer.",
    };
  }

  if (!DEFAULT_AUTOMATIC_KINDS.has(occurrence.kind)) {
    return {
      eligible: false,
      reason:
        occurrence.kind === "template_literal"
          ? "dynamic_expression"
          : "unsupported_kind",
      explanation:
        "This finding type requires review before code replacement.",
    };
  }

  /**
   * Enterprise Rule #022
   * Safe Translation Eligibility
   *
   * Executable JavaScript and TypeScript expressions must never
   * be treated as user-facing translation text.
   */
  const candidateText =
    occurrence.text.trim();

  const containsCodeOperator =
    /(?:===|!==|==|!=|>=|<=|&&|\|\||=>|[<>]=?|\+\+|--|\?\?)/.test(
      candidateText,
    );

  const containsPropertyAccess =
    /\b[A-Za-z_$][A-Za-z0-9_$]*\s*\.\s*[A-Za-z_$][A-Za-z0-9_$]*\b/.test(
      candidateText,
    );

  const containsCodeDelimiters =
    /[()[\]{};]/.test(candidateText);

  const looksLikeCamelCaseIdentifier =
    /^[a-z_$][A-Za-z0-9_$]*$/.test(candidateText) &&
    /[A-Z]/.test(candidateText);

  const looksLikeOperationalIdentifier =
    /^(?:selected|current|previous|next|is|has|can|should|show|hide|total|filtered|displayed|available|records|applications|transactions)[A-Za-z0-9_$]*$/.test(
      candidateText,
    );

  const looksLikeLengthExpression =
    /\.length\b/.test(candidateText);

  const looksLikeExecutableCode =
    containsCodeOperator ||
    containsPropertyAccess ||
    containsCodeDelimiters ||
    looksLikeCamelCaseIdentifier ||
    looksLikeOperationalIdentifier ||
    looksLikeLengthExpression;

  if (looksLikeExecutableCode) {
    return {
      eligible: false,
      reason: "unsupported_kind",
      explanation:
        "Enterprise Rule #022 rejected this finding because it resembles executable JavaScript or TypeScript rather than user-facing text.",
    };
  }

  if (
    occurrence.confidence <
    input.options.minimumAutomaticConfidence
  ) {
    return {
      eligible: false,
      reason: "low_confidence",
      explanation: `Confidence ${occurrence.confidence.toFixed(
        2,
      )} is below the automatic threshold ${input.options.minimumAutomaticConfidence.toFixed(
        2,
      )}.`,
    };
  }

  return {
    eligible: true,
  };
}

/**
 * Returns all indexes where a value appears.
 */
function findAllIndexes(
  source: string,
  value: string,
): number[] {
  const indexes: number[] = [];

  if (!value) {
    return indexes;
  }

  let startIndex = 0;

  while (startIndex < source.length) {
    const foundIndex = source.indexOf(
      value,
      startIndex,
    );

    if (foundIndex === -1) {
      break;
    }

    indexes.push(foundIndex);

    startIndex =
      foundIndex +
      Math.max(value.length, 1);
  }

  return indexes;
}

/**
 * Returns the absolute character index for a line and column.
 */
function lineColumnToIndex(
  source: string,
  line: number,
  column: number,
): number {
  const lines = source.split("\n");

  let index = 0;

  const targetLine = Math.max(1, line);
  const targetColumn = Math.max(1, column);

  for (
    let currentLine = 1;
    currentLine < targetLine &&
    currentLine <= lines.length;
    currentLine += 1
  ) {
    index +=
      (lines[currentLine - 1]?.length ?? 0) + 1;
  }

  return index + targetColumn - 1;
}

/**
 * Locates one occurrence in the original source.
 *
 * The detector may analyze comment-stripped source. Therefore,
 * this function uses the line/column as an anchor and searches
 * for the original text near that location.
 */
function locateOccurrence(input: {
  source: string;
  occurrence: HardcodedTextOccurrence;
}):
  | {
      success: true;
      startIndex: number;
      endIndex: number;
    }
  | {
      success: false;
      reason:
        | "source_match_missing"
        | "ambiguous_source_match";
    } {
  const expectedIndex = lineColumnToIndex(
    input.source,
    input.occurrence.line,
    input.occurrence.column,
  );

  const candidates = findAllIndexes(
    input.source,
    input.occurrence.text,
  );

  if (candidates.length === 0) {
    return {
      success: false,
      reason: "source_match_missing",
    };
  }

  const ranked = candidates
    .map((candidate) => ({
      candidate,
      distance: Math.abs(candidate - expectedIndex),
    }))
    .sort(
      (first, second) =>
        first.distance - second.distance,
    );

  const closest = ranked[0];

  if (!closest) {
    return {
      success: false,
      reason: "source_match_missing",
    };
  }

  if (
    ranked.length > 1 &&
    ranked[1] &&
    ranked[1].distance === closest.distance
  ) {
    return {
      success: false,
      reason: "ambiguous_source_match",
    };
  }

  const textStartIndex = closest.candidate;

const textEndIndex =
  closest.candidate +
  input.occurrence.text.length;

/**
 * JSX attribute values are normally enclosed in quotation marks:
 *
 * placeholder="Meeting notes"
 *
 * The replacement must remove the quotation marks as well:
 *
 * placeholder={t("form.placeholder.meeting_notes")}
 */
if (
  input.occurrence.kind === "jsx_attribute"
) {
  const openingCharacter =
    input.source[textStartIndex - 1];

  const closingCharacter =
    input.source[textEndIndex];

  const hasMatchingQuotes =
    (openingCharacter === `"` &&
      closingCharacter === `"`) ||
    (openingCharacter === `'` &&
      closingCharacter === `'`);

  if (hasMatchingQuotes) {
    return {
      success: true,
      startIndex:
        textStartIndex - 1,
      endIndex:
        textEndIndex + 1,
    };
  }

  return {
    success: false,
    reason:
      "source_match_missing",
  };
}

return {
  success: true,
  startIndex:
    textStartIndex,
  endIndex:
    textEndIndex,
};
}

/**
 * Converts the detector replacement into valid source syntax.
 */
function createSourceReplacement(
  occurrence: HardcodedTextOccurrence,
): string {
  const replacement =
    occurrence.suggestedReplacement;

  if (occurrence.kind === "jsx_text") {
    return replacement;
  }

  if (occurrence.kind === "jsx_attribute") {
    return replacement;
  }

  return replacement;
}

/**
 * Detects a translation function already present in the file.
 */
function hasTranslationRuntime(
  source: string,
  translationFunctionName: string,
): boolean {
  const functionPattern = new RegExp(
    `\\b${translationFunctionName}\\s*\\(`,
  );

  return functionPattern.test(source);
}

/**
 * Determines whether a file is explicitly a client component.
 */
function isClientComponent(source: string): boolean {
  return /^\s*["']use client["'];?/m.test(source);
}

/**
 * Injects a translation runtime into a client component.
 *
 * This implementation supports the existing EPEW language hook
 * pattern only when the component is already a client component.
 *
 * Server components are sent to review because injecting a client
 * hook would change their rendering behavior.
 */
function injectTranslationRuntime(input: {
  source: string;
  namespace: string;
  hookImport: string;
  hookName: string;
  translationFunctionName: string;
}):
  | {
      success: true;
      source: string;
      injected: boolean;
    }
  | {
      success: false;
      reason:
        | "server_component"
        | "translation_runtime_missing";
    } {
  if (
    hasTranslationRuntime(
      input.source,
      input.translationFunctionName,
    )
  ) {
    return {
      success: true,
      source: input.source,
      injected: false,
    };
  }

  if (!isClientComponent(input.source)) {
    return {
      success: false,
      reason: "server_component",
    };
  }

  const importStatement = `import { ${input.hookName} } from "${input.hookImport}";`;

  let transformed = input.source;

  if (
    !transformed.includes(
      `import { ${input.hookName} }`,
    )
  ) {
    const directiveMatch = transformed.match(
      /^\s*["']use client["'];?\s*/,
    );

    const insertionIndex =
      directiveMatch?.[0].length ?? 0;

    transformed = [
      transformed.slice(0, insertionIndex),
      insertionIndex > 0 ? "\n" : "",
      importStatement,
      "\n",
      transformed.slice(insertionIndex),
    ].join("");
  }

  const componentPattern =
    /export\s+default\s+(?:async\s+)?function\s+[A-Za-z_$][\w$]*\s*\([^)]*\)\s*\{/;

  const componentMatch =
    componentPattern.exec(transformed);

  if (!componentMatch) {
    return {
      success: false,
      reason: "translation_runtime_missing",
    };
  }

  const bodyStart =
    componentMatch.index +
    componentMatch[0].length;

  const runtimeStatement =
  `\n  const { ${input.translationFunctionName} } = ${input.hookName}();\n`;

  transformed = [
    transformed.slice(0, bodyStart),
    runtimeStatement,
    transformed.slice(bodyStart),
  ].join("");

  return {
    success: true,
    source: transformed,
    injected: true,
  };
}

/**
 * Performs lightweight source validation.
 */
function validateTransformedSource(
  source: string,
): string[] {
  const errors: string[] = [];

  const openingBraces =
    (source.match(/\{/g) ?? []).length;

  const closingBraces =
    (source.match(/\}/g) ?? []).length;

  const openingParentheses =
    (source.match(/\(/g) ?? []).length;

  const closingParentheses =
    (source.match(/\)/g) ?? []).length;

  if (openingBraces !== closingBraces) {
    errors.push(
      "Curly-brace count changed or is unbalanced.",
    );
  }

  if (
    openingParentheses !== closingParentheses
  ) {
    errors.push(
      "Parenthesis count changed or is unbalanced.",
    );
  }

  if (
    source.includes(
      "{t(\"undefined\")}",
    ) ||
    source.includes(
      "t(\"undefined\")",
    )
  ) {
    errors.push(
      "An undefined translation key was generated.",
    );
  }

  return errors;
}

/**
 * Creates a transformation plan for one file.
 */
async function createFilePlan(input: {
  projectRoot: string;
  sourceFile: string;
  occurrences: HardcodedTextOccurrence[];
  options: typeof DEFAULT_OPTIONS &
    SafeCodeTransformerOptions;
}): Promise<{
  plan: SourceFileTransformationPlan;
  reviewItems: TransformationReviewItem[];
}> {
  const absolutePath = path.resolve(
    input.projectRoot,
    input.sourceFile,
  );

  const reviewItems: TransformationReviewItem[] = [];

  const emptyPlan = (
    originalSource: string,
  ): SourceFileTransformationPlan => ({
    id: createStableId(
      "source-file-transformation-plan",
      input.sourceFile,
      nowIso(),
    ),

    sourceFile: input.sourceFile,
    absolutePath: normalizePath(absolutePath),

    namespace:
      input.occurrences[0]?.suggestedNamespace ??
      input.occurrences[0]?.namespace ??
      null,

    originalSource,
    transformedSource: originalSource,

    replacements: [],

    requiresTranslationRuntime: false,
    translationRuntimePresent: false,
    translationRuntimeInjected: false,

    status: "skipped",

    reviewReasons: [],
    warnings: [],
    errors: [],
  });

  if (!(await pathExists(absolutePath))) {
    const plan = emptyPlan("");

    plan.status = "review_required";
    plan.reviewReasons.push(
      "source_file_missing",
    );

    for (const occurrence of input.occurrences) {
      reviewItems.push(
        createReviewItem({
          occurrence,
          reason: "source_file_missing",
          explanation:
            "The source file could not be found.",
        }),
      );
    }

    return {
      plan,
      reviewItems,
    };
  }

  let originalSource = "";

  try {
    originalSource = await fs.readFile(
      absolutePath,
      "utf8",
    );
  } catch (error) {
    const plan = emptyPlan("");

    plan.status = "failed";

    plan.errors.push(
      error instanceof Error
        ? error.message
        : "Unable to read source file.",
    );

    return {
      plan,
      reviewItems,
    };
  }

  const plan = emptyPlan(originalSource);

  const eligibleOccurrences: HardcodedTextOccurrence[] =
    [];

  for (const occurrence of input.occurrences) {
    const eligibility = getAutomaticEligibility({
      occurrence,
      options: input.options,
    });

    if (!eligibility.eligible) {
      plan.reviewReasons.push(
        eligibility.reason,
      );

      reviewItems.push(
        createReviewItem({
          occurrence,
          reason: eligibility.reason,
          explanation: eligibility.explanation,
        }),
      );

      continue;
    }

    eligibleOccurrences.push(occurrence);
  }

  const replacements: SourceTextReplacement[] = [];

  for (const occurrence of eligibleOccurrences) {
    const namespace =
      occurrence.suggestedNamespace ??
      occurrence.namespace;

    if (!namespace) {
      continue;
    }

    const location = locateOccurrence({
      source: originalSource,
      occurrence,
    });

    if (!location.success) {
      plan.reviewReasons.push(location.reason);

      reviewItems.push(
        createReviewItem({
          occurrence,
          reason: location.reason,
          explanation:
            location.reason ===
            "ambiguous_source_match"
              ? "The same source text appears in multiple equally likely locations."
              : "The source text could not be found in the original file.",
        }),
      );

      continue;
    }

    replacements.push({
      id: createStableId(
        "source-text-replacement",
        occurrence.id,
        location.startIndex,
      ),

      sourceFile: occurrence.sourceFile,
      namespace,

      occurrenceId: occurrence.id,
      kind: occurrence.kind,

      key: occurrence.suggestedKey,
      fullKey: occurrence.suggestedFullKey,
      masterValue: occurrence.text,

      originalText: occurrence.text,
      originalExpression:
        occurrence.rawExpression,

      replacementExpression:
        createSourceReplacement(occurrence),

      startIndex: location.startIndex,
      endIndex: location.endIndex,

      line: occurrence.line,
      column: occurrence.column,

      confidence: occurrence.confidence,
    });
  }

  if (replacements.length === 0) {
    plan.status =
      reviewItems.length > 0
        ? "review_required"
        : "skipped";

    return {
      plan,
      reviewItems,
    };
  }

  const namespace = replacements[0]?.namespace;

  if (!namespace) {
    plan.status = "review_required";
    plan.reviewReasons.push(
      "missing_namespace",
    );

    return {
      plan,
      reviewItems,
    };
  }

  let transformedSource = originalSource;

  const runtimePresent = hasTranslationRuntime(
    transformedSource,
    input.options.translationFunctionName,
  );

  plan.requiresTranslationRuntime = true;
  plan.translationRuntimePresent =
    runtimePresent;

  if (
    !runtimePresent &&
    input.options.injectTranslationRuntime
  ) {
    const runtimeResult =
      injectTranslationRuntime({
        source: transformedSource,
        namespace,
        hookImport:
          input.options.translationHookImport,
        hookName:
          input.options.translationHookName,
        translationFunctionName:
          input.options.translationFunctionName,
      });

    if (!runtimeResult.success) {
      plan.status = "review_required";
      plan.reviewReasons.push(
        runtimeResult.reason,
      );

      for (const occurrence of eligibleOccurrences) {
        reviewItems.push(
          createReviewItem({
            occurrence,
            reason: runtimeResult.reason,
            explanation:
              runtimeResult.reason ===
              "server_component"
                ? "The file is a server component. A client translation hook cannot be injected safely."
                : "The transformer could not determine where to inject the translation runtime.",
          }),
        );
      }

      return {
        plan,
        reviewItems,
      };
    }

    transformedSource = runtimeResult.source;

    plan.translationRuntimeInjected =
      runtimeResult.injected;
  }

  /**
   * Recalculate source locations after runtime injection.
   */
  const finalReplacements: SourceTextReplacement[] =
    [];

  for (const replacement of replacements) {
    const occurrence = eligibleOccurrences.find(
      (item) =>
        item.id === replacement.occurrenceId,
    );

    if (!occurrence) {
      continue;
    }

    const location = locateOccurrence({
      source: transformedSource,
      occurrence,
    });

    if (!location.success) {
      reviewItems.push(
        createReviewItem({
          occurrence,
          reason: location.reason,
          explanation:
            "The source location became ambiguous after translation-runtime injection.",
        }),
      );

      continue;
    }

    finalReplacements.push({
      ...replacement,
      startIndex: location.startIndex,
      endIndex: location.endIndex,
    });
  }

  /**
   * Apply from the bottom of the file upward so character offsets
   * remain stable.
   */
  for (const replacement of [...finalReplacements].sort(
    (first, second) =>
      second.startIndex - first.startIndex,
  )) {
    transformedSource = [
      transformedSource.slice(
        0,
        replacement.startIndex,
      ),
      replacement.replacementExpression,
      transformedSource.slice(
        replacement.endIndex,
      ),
    ].join("");
  }

  const validationErrors =
    validateTransformedSource(transformedSource);

  if (validationErrors.length > 0) {
    plan.status = "review_required";
    plan.reviewReasons.push(
      "syntax_validation_failed",
    );
    plan.errors.push(...validationErrors);

    for (const occurrence of eligibleOccurrences) {
      reviewItems.push(
        createReviewItem({
          occurrence,
          reason:
            "syntax_validation_failed",
          explanation:
            validationErrors.join(" "),
        }),
      );
    }

    return {
      plan,
      reviewItems,
    };
  }

  plan.namespace = namespace;
  plan.replacements = finalReplacements;
  plan.transformedSource = transformedSource;

  plan.status =
    finalReplacements.length > 0
      ? "planned"
      : "review_required";

  return {
    plan,
    reviewItems,
  };
}

/**
 * Creates English and target-language namespace files.
 */
async function generateNamespaces(input: {
  projectRoot: string;
  messagesRoot: string;
  occurrences: HardcodedTextOccurrence[];
  preserveExisting: boolean;
  generateEnglish: boolean;
  generateTargets: boolean;
  translationProvider?: EnterpriseTranslationProvider;
}): Promise<NamespaceGenerationResult> {
  const result: NamespaceGenerationResult = {
    generatedFiles: [],
    updatedFiles: [],
    unchangedFiles: [],

    namespacesCreated: [],
    namespacesUpdated: [],

    keysCreated: 0,
    keysPreserved: 0,

    errors: [],
  };

  const grouped = new Map<
    string,
    Map<string, GeneratedNamespaceEntry>
  >();

  for (const occurrence of input.occurrences) {
    const namespace =
      occurrence.suggestedNamespace ??
      occurrence.namespace;

    if (!namespace) {
      continue;
    }

    grouped.set(
      namespace,
      grouped.get(namespace) ?? new Map(),
    );

    const namespaceEntries =
      grouped.get(namespace);

    if (!namespaceEntries) {
      continue;
    }

    const existing =
      namespaceEntries.get(
        occurrence.suggestedKey,
      );

    if (existing) {
      existing.occurrenceIds.push(
        occurrence.id,
      );

      continue;
    }

    namespaceEntries.set(
      occurrence.suggestedKey,
      {
        namespace,
        key: occurrence.suggestedKey,
        value: occurrence.text,
        occurrenceIds: [occurrence.id],
      },
    );
  }

  for (const [
    namespace,
    entriesMap,
  ] of grouped.entries()) {
    const entries = [...entriesMap.values()];

    const englishPath = path.resolve(
      input.projectRoot,
      input.messagesRoot,
      "en",
      `${namespace}.json`,
    );

    const englishResult =
      await readJsonObject(englishPath);

    if (englishResult.error) {
      result.errors.push(
        `${toProjectRelativePath(
          input.projectRoot,
          englishPath,
        )}: ${englishResult.error}`,
      );

      continue;
    }

    const englishObject =
      englishResult.data;

    let englishChanged = false;

    for (const entry of entries) {
      const setResult = setNestedValue(
        englishObject,
        entry.key,
        entry.value,
        input.preserveExisting,
      );

      if (setResult.created) {
        result.keysCreated += 1;
        englishChanged = true;
      }

      if (setResult.preserved) {
        result.keysPreserved += 1;
      }
    }

    if (input.generateEnglish) {
      const englishRelative =
        toProjectRelativePath(
          input.projectRoot,
          englishPath,
        );

      if (!englishResult.exists) {
        await writeJsonObject(
          englishPath,
          englishObject,
        );

        result.generatedFiles.push(
          englishRelative,
        );

        result.namespacesCreated.push(
          namespace,
        );
      } else if (englishChanged) {
        await writeJsonObject(
          englishPath,
          englishObject,
        );

        result.updatedFiles.push(
          englishRelative,
        );

        result.namespacesUpdated.push(
          namespace,
        );
      } else {
        result.unchangedFiles.push(
          englishRelative,
        );
      }
    }

    if (!input.generateTargets) {
      continue;
    }

    for (const language of TARGET_LANGUAGES) {
      const targetPath = path.resolve(
        input.projectRoot,
        input.messagesRoot,
        language,
        `${namespace}.json`,
      );

      const targetResult =
        await readJsonObject(targetPath);

      if (targetResult.error) {
        result.errors.push(
          `${toProjectRelativePath(
            input.projectRoot,
            targetPath,
          )}: ${targetResult.error}`,
        );

        continue;
      }

      const targetObject =
        targetResult.data;

      let targetChanged = false;

      for (const entry of entries) {
        const existingValue =
          getNestedValue(
            targetObject,
            entry.key,
          );

        if (
          input.preserveExisting &&
          typeof existingValue === "string" &&
          existingValue.trim() !== ""
        ) {
          continue;
        }

        let translatedValue =
          entry.value;

        if (input.translationProvider) {
          try {
            const providerValue =
              await input.translationProvider({
                sourceLanguage: "en",
                targetLanguage: language,
                namespace,
                key: entry.key,
                sourceText: entry.value,
              });

            if (providerValue.trim()) {
              translatedValue =
                providerValue.trim();
            }
          } catch (error) {
            result.errors.push(
              `Translation provider failed for ${language}/${namespace}.${entry.key}: ${
                error instanceof Error
                  ? error.message
                  : "Unknown translation-provider error."
              }`,
            );
          }
        }

        const setResult = setNestedValue(
          targetObject,
          entry.key,
          translatedValue,
          false,
        );

        if (
          setResult.created ||
          existingValue !== translatedValue
        ) {
          targetChanged = true;
        }
      }

      const targetRelative =
        toProjectRelativePath(
          input.projectRoot,
          targetPath,
        );

      if (!targetResult.exists) {
        await writeJsonObject(
          targetPath,
          targetObject,
        );

        result.generatedFiles.push(
          targetRelative,
        );
      } else if (targetChanged) {
        await writeJsonObject(
          targetPath,
          targetObject,
        );

        result.updatedFiles.push(
          targetRelative,
        );
      } else {
        result.unchangedFiles.push(
          targetRelative,
        );
      }
    }
  }

  result.generatedFiles = uniqueValues(
    result.generatedFiles,
  ).sort();

  result.updatedFiles = uniqueValues(
    result.updatedFiles,
  ).sort();

  result.unchangedFiles = uniqueValues(
    result.unchangedFiles,
  ).sort();

  result.namespacesCreated = uniqueValues(
    result.namespacesCreated,
  ).sort();

  result.namespacesUpdated = uniqueValues(
    result.namespacesUpdated,
  ).sort();

  return result;
}

/**
 * Creates a source backup.
 */
async function createSourceBackup(input: {
  projectRoot: string;
  backupRoot: string;
  sourceFile: string;
  absolutePath: string;
}): Promise<string> {
  const timestamp = nowIso()
    .replaceAll(":", "-")
    .replaceAll(".", "-");

  const backupPath = path.resolve(
    input.projectRoot,
    input.backupRoot,
    timestamp,
    input.sourceFile,
  );

  await ensureDirectory(
    path.dirname(backupPath),
  );

  await fs.copyFile(
    input.absolutePath,
    backupPath,
  );

  return toProjectRelativePath(
    input.projectRoot,
    backupPath,
  );
}

/**
 * Writes the transformation review queue.
 */
async function saveReviewQueue(input: {
  projectRoot: string;
  reviewItems: TransformationReviewItem[];
}): Promise<string> {
  const reviewPath = path.resolve(
    input.projectRoot,
    "data/enterprise/ibos/translation-center/registry/transformation-review-queue.json",
  );

  await writeJsonObject(reviewPath, {
    platform: "EPEW-EDE-IBOS",
    registry:
      "TRANSLATION_TRANSFORMATION_REVIEW_QUEUE",
    generatedAt: nowIso(),
    totalItems: input.reviewItems.length,
    items: input.reviewItems,
  });

  return toProjectRelativePath(
    input.projectRoot,
    reviewPath,
  );
}

/**
 * Executes the Safe Code Transformer.
 */
export async function runSafeCodeTransformer(
  analysis: ProjectHardcodedTextAnalysis,
  transformerOptions: SafeCodeTransformerOptions = {},
): Promise<SafeCodeTransformerResult> {
  const startedAt = nowIso();
  const startTime = Date.now();

  const options = {
    ...DEFAULT_OPTIONS,
    ...transformerOptions,
  };

  const projectRoot = path.resolve(
    transformerOptions.projectRoot ??
      process.cwd(),
  );

  const transformationId = createStableId(
    "safe-code-transformation",
    projectRoot,
    startedAt,
    analysis.totalOccurrences,
  );

  const includeFileSet =
    transformerOptions.includeFiles
      ? new Set(
          transformerOptions.includeFiles.map(
            normalizePath,
          ),
        )
      : null;

  const excludePatterns =
    transformerOptions.excludeFilePatterns ??
    [];

  const selectedOccurrences =
    analysis.occurrences.filter(
      (occurrence) => {
        const normalizedFile =
          normalizePath(
            occurrence.sourceFile,
          );

        if (
          includeFileSet &&
          !includeFileSet.has(normalizedFile)
        ) {
          return false;
        }

        if (
          excludePatterns.some((pattern) =>
            pattern.test(normalizedFile),
          )
        ) {
          return false;
        }

        return true;
      },
    );

  const fileGroups = new Map<
    string,
    HardcodedTextOccurrence[]
  >();

  for (const occurrence of selectedOccurrences) {
    fileGroups.set(
      occurrence.sourceFile,
      fileGroups.get(
        occurrence.sourceFile,
      ) ?? [],
    );

    fileGroups
      .get(occurrence.sourceFile)
      ?.push(occurrence);
  }

  const filePlans: SourceFileTransformationPlan[] =
    [];

  const reviewQueue: TransformationReviewItem[] =
    [];

  for (const [
    sourceFile,
    occurrences,
  ] of [...fileGroups.entries()].slice(
    0,
    options.maximumFilesToModify,
  )) {
    const filePlanResult =
      await createFilePlan({
        projectRoot,
        sourceFile,
        occurrences,
        options,
      });

    filePlans.push(
      filePlanResult.plan,
    );

    reviewQueue.push(
      ...filePlanResult.reviewItems,
    );
  }

  const automaticallyPlannedOccurrences =
    filePlans.reduce(
      (sum, plan) =>
        sum + plan.replacements.length,
      0,
    );

  /**
   * Generate namespaces only for safely planned replacements.
   */
  const plannedOccurrenceIds = new Set(
    filePlans.flatMap((plan) =>
      plan.replacements.map(
        (replacement) =>
          replacement.occurrenceId,
      ),
    ),
  );

  const plannedOccurrences =
    selectedOccurrences.filter(
      (occurrence) =>
        plannedOccurrenceIds.has(
          occurrence.id,
        ),
    );

  const namespaceGeneration =
    await generateNamespaces({
      projectRoot,
      messagesRoot: options.messagesRoot,
      occurrences: plannedOccurrences,
      preserveExisting:
        options.preserveExistingTranslations,
      generateEnglish:
        options.generateEnglishNamespaces,
      generateTargets:
        options.generateTargetNamespaces,
      translationProvider:
        transformerOptions.translationProvider,
    });

  const backupFiles: string[] = [];

  const generatedFiles = [
    ...namespaceGeneration.generatedFiles,
  ];

  const updatedFiles = [
    ...namespaceGeneration.updatedFiles,
  ];

  const skippedFiles: string[] = [];

  const errors = [
    ...namespaceGeneration.errors,
  ];

  let appliedOccurrences = 0;

  if (options.applyChanges) {
    for (const plan of filePlans) {
      if (plan.status !== "planned") {
        skippedFiles.push(
          plan.sourceFile,
        );

        continue;
      }

      try {
        if (options.createBackups) {
          const backupFile =
            await createSourceBackup({
              projectRoot,
              backupRoot:
                options.backupRoot,
              sourceFile:
                plan.sourceFile,
              absolutePath:
                plan.absolutePath,
            });

          backupFiles.push(
            backupFile,
          );
        }

        await fs.writeFile(
          plan.absolutePath,
          plan.transformedSource,
          "utf8",
        );

        plan.status = "applied";

        appliedOccurrences +=
          plan.replacements.length;

        updatedFiles.push(
          plan.sourceFile,
        );
      } catch (error) {
        plan.status = "failed";

        const message =
          error instanceof Error
            ? error.message
            : "Unknown source-writing error.";

        plan.errors.push(message);

        errors.push(
          `${plan.sourceFile}: ${message}`,
        );
      }
    }
  } else {
    for (const plan of filePlans) {
      if (plan.status !== "planned") {
        skippedFiles.push(
          plan.sourceFile,
        );
      }
    }
  }

  const reviewQueueFile =
    await saveReviewQueue({
      projectRoot,
      reviewItems: reviewQueue,
    });

  updatedFiles.push(
    reviewQueueFile,
  );

  const completedAt = nowIso();

  const buildResult: TranslationBuildResult = {
    success:
      errors.length === 0 &&
      (!options.applyChanges ||
        filePlans.every(
          (plan) =>
            plan.status !== "failed",
        )),

    buildId: transformationId,

    startedAt,
    completedAt,

    generatedFiles:
      uniqueValues(
        generatedFiles,
      ).sort(),

    updatedFiles:
      uniqueValues(
        updatedFiles,
      ).sort(),

    skippedFiles:
      uniqueValues(
        skippedFiles,
      ).sort(),

    queueItemsCreated:
      reviewQueue.length,

    errors:
      uniqueValues(errors),
  };

  return {
    success: buildResult.success,

    transformationId,

    platform: "EPEW-EDE-IBOS",
    engine: "SAFE_CODE_TRANSFORMER",
    version:
      IBOS_SAFE_CODE_TRANSFORMER_VERSION,

    startedAt,
    completedAt,
    durationMs:
      Date.now() - startTime,

    mode:
      options.applyChanges
        ? "apply"
        : "preview",

    analyzedOccurrences:
      selectedOccurrences.length,

    automaticallyPlannedOccurrences,

    appliedOccurrences,

    reviewRequiredOccurrences:
      reviewQueue.length,

    filePlans,
    reviewQueue,

    namespaceGeneration,

    backupFiles:
      uniqueValues(
        backupFiles,
      ).sort(),

    generatedFiles:
      buildResult.generatedFiles,

    updatedFiles:
      buildResult.updatedFiles,

    skippedFiles:
      buildResult.skippedFiles,

    errors:
      buildResult.errors,

    buildResult,
  };
}

/**
 * Runs a safe preview without modifying source files.
 */
export async function previewSafeCodeTransformation(
  analysis: ProjectHardcodedTextAnalysis,
  options: Omit<
    SafeCodeTransformerOptions,
    "applyChanges"
  > = {},
): Promise<SafeCodeTransformerResult> {
  return runSafeCodeTransformer(
    analysis,
    {
      ...options,
      applyChanges: false,
    },
  );
}

/**
 * Applies approved safe transformations.
 */
export async function applySafeCodeTransformation(
  analysis: ProjectHardcodedTextAnalysis,
  options: Omit<
    SafeCodeTransformerOptions,
    "applyChanges"
  > = {},
): Promise<SafeCodeTransformerResult> {
  return runSafeCodeTransformer(
    analysis,
    {
      ...options,
      applyChanges: true,
    },
  );
}

/**
 * Returns files that can be transformed automatically.
 */
export function getAutomaticallyTransformableFiles(
  result: SafeCodeTransformerResult,
): SourceFileTransformationPlan[] {
  return result.filePlans.filter(
    (plan) =>
      plan.status === "planned" ||
      plan.status === "applied",
  );
}

/**
 * Returns files requiring human or agent review.
 */
export function getFilesRequiringTransformationReview(
  result: SafeCodeTransformerResult,
): SourceFileTransformationPlan[] {
  return result.filePlans.filter(
    (plan) =>
      plan.status === "review_required",
  );
}