"use client";
import {useEffect,useState,FormEvent} from "react";
import {useEpewLanguage,LanguageSelector} from "@/app/components/EpewLanguage";
type Thread={id:string;subject:string;recipient:string;internal:boolean;supporter_id:string;created_by:string;updated_at:string;sentByMe?:boolean};
type Message={id:string;sender_name:string;body:string;created_at:string};
type Doc={id:string;name:string;created_at:string};
const text={
 en:{title:"Communications",intro:"Your conversations, contacts and documents in one place.",inbox:"Inbox",sent:"Sent",compose:"New message",documents:"Documents",internal:"Team referrals",subject:"Subject",body:"Message",send:"Send message",reply:"Reply",upload:"Upload document",empty:"No messages yet.",contact:"Your additional contact",advisor:"Supporter Relations & Financial Advisor",help:"Questions or concerns? Yamiley is here to help.",recipient:"Send to",choose:"Choose a supporter",refer:"Refer to Samuel / team",letter:"Acknowledgment letter",certificate:"Support participation certificate",print:"Open / download / print",loading:"Loading…",error:"Unable to complete the request.",uploaded:"Document uploaded.",sentOk:"Message sent.",signout:"Sign out",internalHint:"Private staff discussion. Supporters cannot see these messages.",uploadHint:"PDF, PNG or JPEG · maximum 10 MB",refresh:"Refresh",invite:"Invite Yamiley",inviteOk:"Account invitation sent to Yamiley.",thread:"Conversation"},
 ht:{title:"Kominikasyon",intro:"Konvèsasyon, kontak ak dokiman ou yo nan yon sèl kote.",inbox:"Bwat resepsyon",sent:"Mesaj voye",compose:"Nouvo mesaj",documents:"Dokiman",internal:"Referans ekip",subject:"Sijè",body:"Mesaj",send:"Voye mesaj",reply:"Reponn",upload:"Telechaje dokiman",empty:"Pa gen mesaj ankò.",contact:"Kontak adisyonèl ou",advisor:"Relasyon ak Sipòtè & Konseye Finansye",help:"Kesyon oswa enkyetid? Yamiley la pou ede ou.",recipient:"Voye bay",choose:"Chwazi yon sipòtè",refer:"Refere bay Samuel / ekip la",letter:"Lèt rekonesans",certificate:"Sètifika patisipasyon sipò",print:"Ouvri / telechaje / enprime",loading:"Ap chaje…",error:"Nou pa kapab konplete demann lan.",uploaded:"Dokiman telechaje.",sentOk:"Mesaj voye.",signout:"Dekonekte",internalHint:"Diskisyon prive anplwaye yo. Sipòtè yo pa kapab wè mesaj sa yo.",uploadHint:"PDF, PNG oswa JPEG · maksimòm 10 MB",refresh:"Rafrechi",invite:"Envite Yamiley",inviteOk:"Envitasyon kont lan voye bay Yamiley.",thread:"Konvèsasyon"},
 fr:{title:"Communications",intro:"Vos conversations, contacts et documents au même endroit.",inbox:"Boîte de réception",sent:"Envoyés",compose:"Nouveau message",documents:"Documents",internal:"Demandes à l’équipe",subject:"Objet",body:"Message",send:"Envoyer",reply:"Répondre",upload:"Téléverser un document",empty:"Aucun message.",contact:"Votre contact supplémentaire",advisor:"Relations avec les soutiens et conseillère financière",help:"Une question ? Yamiley est là pour vous aider.",recipient:"Destinataire",choose:"Choisir un soutien",refer:"Transmettre à Samuel / équipe",letter:"Lettre de reconnaissance",certificate:"Certificat de participation",print:"Ouvrir / télécharger / imprimer",loading:"Chargement…",error:"Impossible de terminer la demande.",uploaded:"Document téléversé.",sentOk:"Message envoyé.",signout:"Déconnexion",internalHint:"Discussion privée entre collaborateurs, invisible aux soutiens.",uploadHint:"PDF, PNG ou JPEG · maximum 10 Mo",refresh:"Actualiser",invite:"Inviter Yamiley",inviteOk:"Invitation envoyée à Yamiley.",thread:"Conversation"},
 es:{title:"Comunicaciones",intro:"Sus conversaciones, contactos y documentos en un solo lugar.",inbox:"Bandeja de entrada",sent:"Enviados",compose:"Nuevo mensaje",documents:"Documentos",internal:"Consultas al equipo",subject:"Asunto",body:"Mensaje",send:"Enviar",reply:"Responder",upload:"Subir documento",empty:"No hay mensajes.",contact:"Su contacto adicional",advisor:"Relaciones con colaboradores y asesora financiera",help:"¿Preguntas? Yamiley está aquí para ayudarle.",recipient:"Destinatario",choose:"Elegir colaborador",refer:"Consultar a Samuel / equipo",letter:"Carta de reconocimiento",certificate:"Certificado de participación",print:"Abrir / descargar / imprimir",loading:"Cargando…",error:"No se pudo completar la solicitud.",uploaded:"Documento subido.",sentOk:"Mensaje enviado.",signout:"Cerrar sesión",internalHint:"Conversación privada del equipo, invisible a colaboradores.",uploadHint:"PDF, PNG o JPEG · máximo 10 MB",refresh:"Actualizar",invite:"Invitar a Yamiley",inviteOk:"Invitación enviada a Yamiley.",thread:"Conversación"}
};
export default function SupporterCommunications({staff=false}:{staff?:boolean}){
 const {language}=useEpewLanguage();const t=text[language];
 const [data,setData]=useState<{identity:{userId:string;name:string;staff:boolean;role?:string};threads:Thread[];documents:Doc[];issuedDocuments:boolean;supporters?:{id:string;full_name:string}[]} | null>(null);
 const [tab,setTab]=useState("inbox"),[selected,setSelected]=useState<Thread|null>(null),[messages,setMessages]=useState<Message[]>([]),[attachments,setAttachments]=useState<Doc[]>([]);
 const [subject,setSubject]=useState(""),[body,setBody]=useState(""),[recipient,setRecipient]=useState("Yamiley Noslen"),[supporterId,setSupporterId]=useState(""),[isInternal,setInternal]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const [docLanguage,setDocLanguage]=useState("en");
 async function call(url:string,options?:RequestInit){const response=await fetch(url,options);const result=await response.json();if(!response.ok)throw new Error(result.error || t.error);return result;}
 async function load(){try{const result=await call("/api/supporters/communications");if(staff&&!result.identity.staff){window.location.assign("/staff/supporter-relations/login");return;}setData(result);}catch(e){setNotice(e instanceof Error?e.message:t.error);}}
 useEffect(()=>{void load();},[]);
 async function open(thread:Thread){setNotice("");setSelected(thread);setBody("");try{const result=await call(`/api/supporters/communications?threadId=${encodeURIComponent(thread.id)}`);setSelected(result.thread);setMessages(result.messages);setAttachments(result.documents);}catch(e){setNotice(e instanceof Error?e.message:t.error);}}
 async function send(event:FormEvent){event.preventDefault();setBusy(true);setNotice("");try{const result=await call("/api/supporters/communications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(selected?{threadId:selected.id,body}:{subject,body,recipient,supporterId,internal:isInternal})});setBody("");setSubject("");setNotice(t.sentOk);await load();const thread={id:result.threadId} as Thread;await open(thread);setTab(isInternal?"internal":"inbox");}catch(e){setNotice(e instanceof Error?e.message:t.error);}finally{setBusy(false);}}
 async function upload(file:File){setBusy(true);try{const form=new FormData();form.set("file",file);if(selected)form.set("threadId",selected.id);await call("/api/supporters/communications/documents",{method:"POST",body:form});setNotice(t.uploaded);await load();if(selected)await open(selected);}catch(e){setNotice(e instanceof Error?e.message:t.error);}finally{setBusy(false);}}
 const button="rounded-xl bg-[#07583d] px-4 py-2 font-semibold text-white disabled:opacity-50";
 const input="w-full rounded-xl border border-slate-300 p-3 text-slate-900";
 return <section className="mx-auto max-w-6xl space-y-5 text-[#06245c]">
  <header className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><h1 className="text-3xl font-bold">{t.title}{staff?` — ${data?.identity.name || "EPEW"}`:""}</h1>{staff&&<LanguageSelector/>}</div><p className="mt-2">{t.intro}</p></header>
  {!staff&&<aside className="rounded-2xl border border-green-200 bg-green-50 p-5"><p className="text-sm font-semibold">{t.contact}</p><h2 className="text-xl font-bold">Yamiley Noslen</h2><p>{t.advisor}</p><a className="underline" href="mailto:ynoslen@epew.us">ynoslen@epew.us</a><p className="mt-2">{t.help}</p></aside>}
  <nav aria-label={t.title} className="flex flex-wrap gap-2">{["inbox","sent","compose","documents",...(staff?["internal"]:[])].map(key=><button key={key} onClick={()=>{setTab(key);setSelected(null);setInternal(key==="internal");setBody("");}} className={tab===key?button:"rounded-xl border bg-white px-4 py-2"}>{t[key as "inbox"]}</button>)}<button className="rounded-xl border bg-white px-4 py-2" onClick={()=>void load()}>{t.refresh}</button></nav>
  {notice&&<p role="status" className="rounded-xl border bg-white p-3">{notice}</p>}
  {!data?<p>{t.loading}</p>:<>
   {tab==="documents"?<div className="rounded-2xl bg-white p-6 space-y-4"><h2 className="text-2xl font-bold">{t.documents}</h2>
    {data.issuedDocuments&&<div className="rounded-xl border p-4 space-y-3"><select aria-label="Document language" value={docLanguage} onChange={e=>setDocLanguage(e.target.value)} className={input}><option value="en">English</option><option value="ht">Kreyòl Ayisyen</option></select>{["letter","certificate"].map(kind=><div key={kind} className="flex flex-wrap justify-between gap-3"><strong>{t[kind as "letter"]}</strong><a className="underline" target="_blank" rel="noopener noreferrer" href={`/api/supporters/certificates?transactionId=bf1ef08b-fbda-4e33-84d6-9a20bd8006dd&language=${docLanguage}&kind=${kind}`}>{t.print}</a></div>)}</div>}
    {data.documents.map(doc=><div key={doc.id} className="flex flex-wrap justify-between gap-3 rounded-xl border p-3"><span>{doc.name}</span><a className="underline" href={`/api/supporters/communications/documents?id=${doc.id}`} target="_blank" rel="noopener noreferrer">{t.print}</a></div>)}
    {!staff&&<label className="block">{t.upload}<input disabled={busy} type="file" accept="application/pdf,image/png,image/jpeg" className="block mt-2" onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value="";}}/><small>{t.uploadHint}</small></label>}
   </div>:<div className="grid gap-5 lg:grid-cols-[minmax(230px,1fr)_2fr]">
    <div className="space-y-3">{tab==="internal"&&<p className="rounded-xl bg-amber-50 p-3">{t.internalHint}</p>}{data.threads.filter(x=>tab==="internal"?x.internal:!x.internal&&(tab!=="sent"||x.sentByMe)).map(thread=><button key={thread.id} onClick={()=>void open(thread)} className="block w-full rounded-xl border bg-white p-4 text-left"><strong>{thread.subject}</strong><p className="text-sm">{thread.recipient}</p><small>{new Date(thread.updated_at).toLocaleString(language)}</small></button>)}{data.threads.length===0&&<p>{t.empty}</p>}</div>
    <div className="space-y-4 rounded-2xl bg-white p-6">
     {selected&&<><h2 className="text-xl font-bold">{selected.subject || t.thread}</h2>{messages.map(m=><article key={m.id} className="rounded-xl bg-slate-50 p-4"><strong>{m.sender_name}</strong><p className="whitespace-pre-wrap mt-2">{m.body}</p><small>{new Date(m.created_at).toLocaleString(language)}</small></article>)}{attachments.map(doc=><a key={doc.id} className="block underline" target="_blank" rel="noopener noreferrer" href={`/api/supporters/communications/documents?id=${doc.id}`}>{doc.name}</a>)}
      <label className="block">{t.upload}<input type="file" disabled={busy} accept="application/pdf,image/png,image/jpeg" className="block mt-2" onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value="";}}/><small>{t.uploadHint}</small></label>
      {staff&&!selected.internal&&<button className="rounded-xl border px-3 py-2" onClick={()=>{setSubject(`Referral: ${selected.subject}`);setBody(`Supporter conversation: ${selected.id}\n\n`);setSelected(null);setInternal(true);setTab("internal");}}>{t.refer}</button>}
     </>}
     <form onSubmit={send} className="space-y-4">
      {!selected&&<><h2 className="text-xl font-bold">{isInternal?t.internal:t.compose}</h2>{isInternal&&<p>{t.internalHint}</p>}{staff&&!isInternal?<label className="block">{t.choose}<select required className={input} value={supporterId} onChange={e=>setSupporterId(e.target.value)}><option value="">{t.choose}</option>{data.supporters?.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label>:!isInternal&&<label className="block">{t.recipient}<select className={input} value={recipient} onChange={e=>setRecipient(e.target.value)}>{["Yamiley Noslen","EPEW Admin","Technical Support","Payment Support","Assigned Coach"].map(r=><option key={r}>{r}</option>)}</select></label>}<label className="block">{t.subject}<input required maxLength={200} className={input} value={subject} onChange={e=>setSubject(e.target.value)}/></label></>}
      <label className="block">{selected?t.reply:t.body}<textarea required maxLength={10000} rows={5} className={input} value={body} onChange={e=>setBody(e.target.value)}/></label><button disabled={busy} className={button}>{t.send}</button>
     </form>
    </div>
   </div>}
   {staff&&data.identity.role==="director"&&<button className={button} disabled={busy} onClick={async()=>{setBusy(true);try{await call("/api/staff/supporter-relations/invite",{method:"POST"});setNotice(t.inviteOk);}catch(e){setNotice(e instanceof Error?e.message:t.error);}finally{setBusy(false);}}}>{t.invite}</button>}
  </>}
 </section>;
}
