const {test}=require('node:test');const assert=require('node:assert/strict');const Module=require('node:module');const original=Module._load;
let user,bound,assignmentAllowed,calls,storageWrites;
const admin={auth:{getUser:async()=>({data:{user},error:null})},storage:{from(){return {upload:async()=>{storageWrites++;return {error:null}},remove:async()=>({error:null}),createSignedUrl:async()=>({data:{signedUrl:'private-link'},error:null})}}}};
const operation=async(actor,action,opts)=>{calls.push({actor,action,opts});if(!bound)throw new Error('Bound coach required');if(opts?.assignment&&!assignmentAllowed)throw new Error('Current assignment required');if(action==='open_document'&&!assignmentAllowed)throw new Error('Current assignment required');if(action==='profile')return {name:'Test Coach',email:user.email,role:'coach',restrictions:['no financial approval','no platform administration']};if(action==='open_document')return {name:'Test.pdf',storage_path:'private/test'};return {saved:true,channel:'EPEW portal'};};
Module._load=function(name,parent,isMain){if(name==='@/lib/supabaseAdmin')return {supabaseAdmin:admin};if(name==='@/lib/coaches/agentAccess')return {coachOperation:operation};return original.apply(this,arguments)};
const {POST}=require('../app/api/coaches/mcp/route.ts');
function reset(){user={id:'user',email:'test-coach@example.invalid',email_confirmed_at:'2026-10-10'};bound=true;assignmentAllowed=true;calls=[];storageWrites=0;}
function req(name='epew_coach_profile',args={},token=true,method='tools/call'){return new Request('https://www.epew.us/api/coaches/mcp',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer test'}:{})},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params:{name,arguments:args}})});}
const assignment='11111111-1111-4111-8111-111111111111';
test('every advertised coach tool requires OAuth and no payment/admin tool exists',async()=>{reset();const j=await(await POST(req('',{},false,'tools/list'))).json();assert.equal(j.result.tools.length,12);assert.ok(j.result.tools.every(t=>t.securitySchemes[0].type==='oauth2'));assert.ok(!j.result.tools.some(t=>/approve_payment|change_role|execute_sql/.test(t.name)));assert.equal(calls.length,0)});
test('anonymous tools return coach metadata challenge',async()=>{reset();const r=await POST(req('',{},false));assert.equal(r.status,401);assert.match(r.headers.get('www-authenticate'),/api\/coaches\/mcp/);assert.equal(calls.length,0)});
test('unconfirmed identity cannot call any operation',async()=>{reset();user.email_confirmed_at=null;assert.equal((await POST(req())).status,401);assert.equal(calls.length,0)});
test('unbound or disabled coach is denied',async()=>{reset();bound=false;assert.equal((await POST(req())).status,403)});
test('profile reports actual verified identity and restrictions',async()=>{reset();const j=await(await POST(req())).json();const p=JSON.parse(j.result.content[0].text);assert.equal(p.role,'coach');assert.equal(p.email,user.email);assert.ok(p.restrictions.includes('no financial approval'))});
test('invalid assignment ID cannot reach write operation',async()=>{reset();const j=await(await POST(req('epew_coach_send_message',{assignment_id:'bad',body:'Test'}))).json();assert.equal(j.result.isError,true);assert.equal(calls.length,1)});
test('cross-coach or revoked assignment is denied by current authorization',async()=>{reset();assignmentAllowed=false;const j=await(await POST(req('epew_coach_send_message',{assignment_id:assignment,body:'Test'}))).json();assert.equal(j.result.isError,true)});
test('authorized message uses verified actor and existing assignment only',async()=>{reset();const j=await(await POST(req('epew_coach_send_message',{assignment_id:assignment,body:'Test reply'}))).json();assert.equal(j.result.isError,undefined);assert.deepEqual(calls[1],{actor:'user',action:'message',opts:{assignment,body:'Test reply'}})});
test('invalid due date cannot create a task',async()=>{reset();const j=await(await POST(req('epew_coach_add_task',{assignment_id:assignment,body:'Task',due_at:'tomorrow'}))).json();assert.equal(j.result.isError,true);assert.equal(calls.length,1)});
test('private document access requires current assignment',async()=>{reset();assignmentAllowed=false;const j=await(await POST(req('epew_coach_open_document',{document_id:assignment}))).json();assert.equal(j.result.isError,true)});
test('fake PDF is rejected before upload',async()=>{reset();const j=await(await POST(req('epew_coach_upload_document',{assignment_id:assignment,name:'fake.pdf',mime_type:'application/pdf',base64:Buffer.from('fake').toString('base64')}))).json();assert.equal(j.result.isError,true);assert.equal(storageWrites,0)});
test('unrelated assignment cannot upload documents',async()=>{reset();assignmentAllowed=false;const j=await(await POST(req('epew_coach_upload_document',{assignment_id:assignment,name:'test.pdf',mime_type:'application/pdf',base64:Buffer.from('%PDF-1.7').toString('base64')}))).json();assert.equal(j.result.isError,true);assert.equal(storageWrites,0)});
test('unsupported financial action is denied',async()=>{reset();assert.equal((await POST(req('approve_payment'))).status,400);assert.equal(calls.length,1)});
