import type { SupportedLocale } from "@/app/components/enterprise/language";

type Section = {
  title: string;
  paragraphs?: string[];
  bullets?: string[];
};

type AgreementCopy = {
  eyebrow: string;
  title: string;
  subtitle?: string;
  intro?: string[];
  sections: Section[];
  versionTitle?: string;
  versionBody?: string;
  returnButton: string;
  acceptReturnButton?: string;
  acceptContinueButton?: string;
  checkboxText?: string;
  acceptanceError?: string;
  acceptanceServerError?: string;
};

const supporterEntrepreneur: Record<SupportedLocale, AgreementCopy> = {
  en: {
    eyebrow: "EPEW Participation Agreement",
    title: "Supporter–Entrepreneur Participation Agreement",
    intro: [
      "This Agreement is between the participating Supporter and the participating Entrepreneur and/or Business.",
      "EPEW (EKERO Partners Empower Wealth LLC) provides the platform, administration, payment coordination, recordkeeping, and mediation support. EPEW is not a party to the direct Supporter–Entrepreneur participation relationship unless stated in a separate agreement."
    ],
    sections: [
      { title: "1. Support Unit", paragraphs: ["One full EPEW Support Unit is $5,200 for a one-year participation period."] },
      { title: "2. Available Support Options", paragraphs: ["The available payment options shown at checkout are determined by the financing path selected by the Entrepreneur.", "For entrepreneurs participating in the standard Funding Queue, the Supporter may choose:"], bullets: ["Weekly: $100 per week toward one Support Unit — participation benefit up to 6%.", "Monthly: $433.34 per month toward one Support Unit — participation benefit up to 6%.", "Annual Paid in Full: $5,200 per Support Unit — participation benefit up to 8%.", "For entrepreneurs participating in the Accelerated Business Financing Path, only Annual Paid in Full is available: $5,200 per Support Unit — participation benefit up to 8%." ] },
      { title: "3. Multiple Units", paragraphs: ["A Supporter may support one or more available units. When multiple units are selected, the checkout amount and payment terms will automatically adjust according to the number of units and payment frequency selected."] },
      { title: "4. Participation Benefit", paragraphs: ["The applicable participation benefit depends upon the payment method selected.", "A Supporter who pays for one or more complete $5,200 units in full may qualify for an annual participation benefit of up to 8%.", "A Supporter who completes a Support Unit through weekly or monthly payments may qualify for an annual participation benefit of up to 6%.", "Participation benefits are not guaranteed and depend on applicable program terms and business performance."] },
      { title: "5. Payment Terms", paragraphs: ["The checkout page will clearly identify the selected payment method, number of units, payment amount, payment frequency, and applicable participation percentage before the Supporter submits the participation request or proceeds to payment.", "The Supporter is responsible only for the payment option selected and confirmed at checkout."] },
      { title: "6. Entrepreneur Financing Path", paragraphs: ["The Supporter understands that the Entrepreneur may participate in either the Funding Queue Path, where weekly, monthly, and annual paid-in-full options may be available, or the Accelerated Business Financing Path, where only full annual Support Units are offered.", "The Entrepreneur’s financing-path election controls the support options displayed by the EPEW platform."] },
      { title: "7. Nature of Participation", paragraphs: ["Participation is voluntary and is intended to support the development, establishment, operation, or growth of the Entrepreneur’s business.", "Participation is not a bank deposit, savings account, or guaranteed financial product. No guaranteed financial return is promised."] },
      { title: "8. EPEW Administration and Mediation", paragraphs: ["EPEW may administer payment processing, participation records, support allocation, reporting, and related program activities.", "If a disagreement arises between the Supporter and Entrepreneur, the parties agree to first allow EPEW to assist with mediation and resolution."] },
      { title: "9. Electronic Acceptance", paragraphs: ["The Supporter may accept this Agreement electronically. The EPEW system may record the Supporter, Entrepreneur, business, selected payment option, number of units, agreement version, date, time, and related transaction information."] }
    ],
    versionTitle: "Agreement Version: September 2026",
    versionBody: "Electronic acceptance of this Agreement is intended to apply to the support option selected by the Supporter at checkout.",
    returnButton: "Return to Support Transaction"
  },
  fr: {
    eyebrow: "Convention de participation EPEW",
    title: "Convention de participation Supporteur–Entrepreneur",
    intro: [
      "La présente Convention est conclue entre le Supporteur participant et l’Entrepreneur et/ou l’Entreprise participante.",
      "EPEW (EKERO Partners Empower Wealth LLC) fournit la plateforme, l’administration, la coordination des paiements, la tenue des dossiers et le soutien à la médiation. EPEW n’est pas partie à la relation directe de participation entre le Supporteur et l’Entrepreneur, sauf disposition contraire dans une convention distincte."
    ],
    sections: [
      { title: "1. Unité de soutien", paragraphs: ["Une Unité de soutien EPEW complète représente 5 200 $ pour une période de participation d’un an."] },
      { title: "2. Options de soutien disponibles", paragraphs: ["Les options de paiement affichées au moment du paiement sont déterminées par le parcours de financement choisi par l’Entrepreneur.", "Pour les entrepreneurs participant à la File de financement standard, le Supporteur peut choisir :"], bullets: ["Hebdomadaire : 100 $ par semaine pour une Unité de soutien — avantage de participation jusqu’à 6 %.", "Mensuel : 433,34 $ par mois pour une Unité de soutien — avantage de participation jusqu’à 6 %.", "Annuel payé intégralement : 5 200 $ par Unité de soutien — avantage de participation jusqu’à 8 %.", "Pour les entrepreneurs participant au Parcours de financement accéléré, seule l’option annuelle payée intégralement est disponible : 5 200 $ par Unité de soutien — avantage de participation jusqu’à 8 %." ] },
      { title: "3. Plusieurs unités", paragraphs: ["Un Supporteur peut soutenir une ou plusieurs unités disponibles. Lorsque plusieurs unités sont sélectionnées, le montant au paiement et les modalités s’ajustent automatiquement selon le nombre d’unités et la fréquence de paiement choisie."] },
      { title: "4. Avantage de participation", paragraphs: ["L’avantage de participation applicable dépend du mode de paiement choisi.", "Un Supporteur qui paie intégralement une ou plusieurs unités complètes de 5 200 $ peut être admissible à un avantage annuel de participation allant jusqu’à 8 %.", "Un Supporteur qui complète une Unité de soutien par paiements hebdomadaires ou mensuels peut être admissible à un avantage annuel de participation allant jusqu’à 6 %.", "Les avantages de participation ne sont pas garantis et dépendent des conditions applicables du programme et de la performance de l’entreprise."] },
      { title: "5. Modalités de paiement", paragraphs: ["La page de paiement indiquera clairement le mode de paiement choisi, le nombre d’unités, le montant, la fréquence et le pourcentage de participation applicable avant que le Supporteur soumette sa demande ou procède au paiement.", "Le Supporteur n’est responsable que de l’option de paiement sélectionnée et confirmée au moment du paiement."] },
      { title: "6. Parcours de financement de l’Entrepreneur", paragraphs: ["Le Supporteur comprend que l’Entrepreneur peut participer soit au Parcours de File de financement, où des options hebdomadaires, mensuelles et annuelles payées intégralement peuvent être offertes, soit au Parcours de financement accéléré, où seules des Unités de soutien annuelles complètes sont offertes.", "Le choix du parcours de financement de l’Entrepreneur détermine les options de soutien affichées par la plateforme EPEW."] },
      { title: "7. Nature de la participation", paragraphs: ["La participation est volontaire et vise à soutenir le développement, l’établissement, l’exploitation ou la croissance de l’entreprise de l’Entrepreneur.", "La participation n’est pas un dépôt bancaire, un compte d’épargne ni un produit financier garanti. Aucun rendement financier garanti n’est promis."] },
      { title: "8. Administration et médiation par EPEW", paragraphs: ["EPEW peut administrer le traitement des paiements, les dossiers de participation, l’allocation du soutien, les rapports et les activités connexes du programme.", "En cas de désaccord entre le Supporteur et l’Entrepreneur, les parties conviennent de permettre d’abord à EPEW d’aider à la médiation et à la résolution."] },
      { title: "9. Acceptation électronique", paragraphs: ["Le Supporteur peut accepter la présente Convention électroniquement. Le système EPEW peut enregistrer le Supporteur, l’Entrepreneur, l’entreprise, l’option de paiement choisie, le nombre d’unités, la version de la Convention, la date, l’heure et les renseignements liés à la transaction."] }
    ],
    versionTitle: "Version de la Convention : septembre 2026",
    versionBody: "L’acceptation électronique de cette Convention s’applique à l’option de soutien choisie par le Supporteur au moment du paiement.",
    returnButton: "Retour à la transaction de soutien"
  },
  es: {
    eyebrow: "Acuerdo de participación EPEW",
    title: "Acuerdo de Participación entre el Colaborador y el Emprendedor",
    intro: [
      "Este Acuerdo se celebra entre el Colaborador participante y el Emprendedor y/o Negocio participante.",
      "EPEW (EKERO Partners Empower Wealth LLC) proporciona la plataforma, administración, coordinación de pagos, mantenimiento de registros y apoyo de mediación. EPEW no es parte de la relación directa de participación entre el Colaborador y el Emprendedor, salvo que se indique lo contrario en un acuerdo separado."
    ],
    sections: [
      { title: "1. Unidad de apoyo", paragraphs: ["Una Unidad de Apoyo EPEW completa equivale a $5,200 por un período de participación de un año."] },
      { title: "2. Opciones de apoyo disponibles", paragraphs: ["Las opciones de pago que aparecen al finalizar la transacción se determinan según la vía de financiamiento elegida por el Emprendedor.", "Para emprendedores en la Cola de Financiamiento estándar, el Colaborador puede elegir:"], bullets: ["Semanal: $100 por semana para una Unidad de Apoyo — beneficio de participación de hasta 6%.", "Mensual: $433.34 por mes para una Unidad de Apoyo — beneficio de participación de hasta 6%.", "Anual pagado en su totalidad: $5,200 por Unidad de Apoyo — beneficio de participación de hasta 8%.", "Para emprendedores en la Vía de Financiamiento Acelerado, solo está disponible la opción anual pagada en su totalidad: $5,200 por Unidad de Apoyo — beneficio de participación de hasta 8%." ] },
      { title: "3. Varias unidades", paragraphs: ["Un Colaborador puede apoyar una o más unidades disponibles. Cuando se seleccionan varias unidades, el monto y los términos de pago se ajustan automáticamente según la cantidad de unidades y la frecuencia elegida."] },
      { title: "4. Beneficio de participación", paragraphs: ["El beneficio de participación aplicable depende del método de pago seleccionado.", "Un Colaborador que pague en su totalidad una o más unidades completas de $5,200 puede calificar para un beneficio anual de participación de hasta 8%.", "Un Colaborador que complete una Unidad de Apoyo mediante pagos semanales o mensuales puede calificar para un beneficio anual de participación de hasta 6%.", "Los beneficios de participación no están garantizados y dependen de los términos aplicables del programa y del desempeño del negocio."] },
      { title: "5. Condiciones de pago", paragraphs: ["La página de pago identificará claramente el método elegido, el número de unidades, el monto, la frecuencia y el porcentaje de participación aplicable antes de que el Colaborador envíe la solicitud o proceda al pago.", "El Colaborador es responsable únicamente por la opción de pago seleccionada y confirmada al finalizar la transacción."] },
      { title: "6. Vía de financiamiento del Emprendedor", paragraphs: ["El Colaborador entiende que el Emprendedor puede participar en la Cola de Financiamiento, donde pueden estar disponibles opciones semanales, mensuales y anuales pagadas en su totalidad, o en la Vía de Financiamiento Acelerado, donde solo se ofrecen Unidades de Apoyo anuales completas.", "La elección de la vía de financiamiento del Emprendedor controla las opciones que muestra la plataforma EPEW."] },
      { title: "7. Naturaleza de la participación", paragraphs: ["La participación es voluntaria y tiene como propósito apoyar el desarrollo, establecimiento, operación o crecimiento del negocio del Emprendedor.", "La participación no es un depósito bancario, cuenta de ahorro ni producto financiero garantizado. No se promete ningún rendimiento financiero garantizado."] },
      { title: "8. Administración y mediación de EPEW", paragraphs: ["EPEW puede administrar el procesamiento de pagos, los registros de participación, la asignación de apoyo, los informes y otras actividades relacionadas con el programa.", "Si surge un desacuerdo entre el Colaborador y el Emprendedor, las partes acuerdan permitir primero que EPEW ayude con la mediación y resolución."] },
      { title: "9. Aceptación electrónica", paragraphs: ["El Colaborador puede aceptar este Acuerdo electrónicamente. El sistema EPEW puede registrar al Colaborador, al Emprendedor, el negocio, la opción de pago seleccionada, el número de unidades, la versión del Acuerdo, la fecha, la hora y la información relacionada con la transacción."] }
    ],
    versionTitle: "Versión del Acuerdo: septiembre de 2026",
    versionBody: "La aceptación electrónica de este Acuerdo se aplica a la opción de apoyo seleccionada por el Colaborador al finalizar la transacción.",
    returnButton: "Volver a la transacción de apoyo"
  },
  ht: {
    eyebrow: "Akò Patisipasyon EPEW",
    title: "Akò Patisipasyon ant Sipòtè ak Antreprenè",
    intro: [
      "Akò sa a fèt ant Sipòtè k ap patisipe a ak Antreprenè ak/oswa Biznis k ap patisipe a.",
      "EPEW (EKERO Partners Empower Wealth LLC) bay platfòm nan, administrasyon, kowòdinasyon peman, kenbe dosye ak sipò medyasyon. EPEW pa yon pati nan relasyon patisipasyon dirèk ant Sipòtè a ak Antreprenè a sof si yon lòt akò ekri di sa klèman."
    ],
    sections: [
      { title: "1. Inite Sipò", paragraphs: ["Yon Inite Sipò EPEW konplè se $5,200 pou yon peryòd patisipasyon yon ane."] },
      { title: "2. Opsyon Sipò ki Disponib", paragraphs: ["Opsyon peman ki parèt nan paj peman an depann de chemen finansman Antreprenè a chwazi a.", "Pou antreprenè ki nan Lis Finansman nòmal la, Sipòtè a ka chwazi:"], bullets: ["Chak semèn: $100 pa semèn pou yon Inite Sipò — benefis patisipasyon jiska 6%.", "Chak mwa: $433.34 pa mwa pou yon Inite Sipò — benefis patisipasyon jiska 6%.", "Anyèl peye nèt: $5,200 pou chak Inite Sipò — benefis patisipasyon jiska 8%.", "Pou antreprenè ki nan Chemen Finansman Akselere a, se sèlman opsyon anyèl peye nèt la ki disponib: $5,200 pou chak Inite Sipò — benefis patisipasyon jiska 8%." ] },
      { title: "3. Plizyè Inite", paragraphs: ["Yon Sipòtè ka sipòte youn oswa plizyè inite ki disponib. Lè li chwazi plizyè inite, kantite lajan ak kondisyon peman yo ajiste otomatikman selon kantite inite ak frekans peman li chwazi a."] },
      { title: "4. Benefis Patisipasyon", paragraphs: ["Benefis patisipasyon ki aplikab la depann de metòd peman yo chwazi a.", "Yon Sipòtè ki peye youn oswa plizyè inite konplè $5,200 an antye ka kalifye pou yon benefis patisipasyon anyèl jiska 8%.", "Yon Sipòtè ki konplete yon Inite Sipò atravè peman chak semèn oswa chak mwa ka kalifye pou yon benefis patisipasyon anyèl jiska 6%.", "Benefis patisipasyon yo pa garanti epi yo depann de kondisyon pwogram ki aplikab yo ak pèfòmans biznis la."] },
      { title: "5. Kondisyon Peman", paragraphs: ["Paj peman an ap montre klèman metòd peman yo chwazi a, kantite inite, kantite lajan, frekans peman ak pousantaj patisipasyon ki aplikab la anvan Sipòtè a soumèt demann lan oswa kontinye ak peman an.", "Sipòtè a responsab sèlman pou opsyon peman li chwazi epi konfime nan paj peman an."] },
      { title: "6. Chemen Finansman Antreprenè a", paragraphs: ["Sipòtè a konprann Antreprenè a ka patisipe swa nan Chemen Lis Finansman an, kote opsyon chak semèn, chak mwa ak anyèl peye nèt ka disponib, oswa nan Chemen Finansman Akselere a, kote se sèlman Inite Sipò anyèl konplè yo ofri.", "Chwa chemen finansman Antreprenè a kontwole opsyon sipò platfòm EPEW la montre."] },
      { title: "7. Nati Patisipasyon an", paragraphs: ["Patisipasyon an volontè epi li fèt pou sipòte devlopman, etablisman, operasyon oswa kwasans biznis Antreprenè a.", "Patisipasyon an pa yon depo labank, kont epay oswa pwodwi finansye garanti. Pa gen okenn retou finansye garanti yo pwomèt."] },
      { title: "8. Administrasyon ak Medyasyon EPEW", paragraphs: ["EPEW ka administre tretman peman, dosye patisipasyon, alokasyon sipò, rapò ak lòt aktivite pwogram lan.", "Si gen yon dezakò ant Sipòtè a ak Antreprenè a, pati yo dakò pou yo kite EPEW ede premye ak medyasyon ak rezolisyon."] },
      { title: "9. Akseptasyon Elektwonik", paragraphs: ["Sipòtè a ka aksepte Akò sa a elektwonikman. Sistèm EPEW la ka anrejistre Sipòtè a, Antreprenè a, biznis la, opsyon peman yo chwazi a, kantite inite, vèsyon Akò a, dat, lè ak enfòmasyon tranzaksyon ki gen rapò."] }
    ],
    versionTitle: "Vèsyon Akò a: Septanm 2026",
    versionBody: "Akseptasyon elektwonik Akò sa a aplike pou opsyon sipò Sipòtè a chwazi nan paj peman an.",
    returnButton: "Retounen nan tranzaksyon sipò a"
  }
};

const supporterEpew: Record<SupportedLocale, AgreementCopy> = {
  en: {
    eyebrow: "EPEW Supporter Agreement",
    title: "EPEW Supporter Platform Participation Agreement",
    subtitle: "Between the Supporter and EPEW (EKERO Partners Empower Wealth LLC)",
    sections: [
      { title: "1. Parties", paragraphs: ["This Supporter Platform Participation Agreement is entered into between EPEW (EKERO Partners Empower Wealth LLC), referred to in this Agreement as “EPEW,” and the individual registered through the EPEW platform as a Supporter, referred to as the “Supporter.”", "This Agreement governs the relationship between EPEW and the Supporter regarding the Supporter’s use of the EPEW platform and participation in the EPEW Entrepreneur Development Ecosystem."] },
      { title: "2. Purpose", paragraphs: ["EPEW operates an entrepreneurship-development and community-support ecosystem designed to connect qualified entrepreneurs with supporters and to provide technology, administration, business-development infrastructure, communication systems, financial administration, and other services necessary to support that ecosystem.", "The Supporter voluntarily elects to participate in the EPEW ecosystem subject to this Agreement and applicable EPEW policies and procedures."] },
      { title: "3. Separate Supporter–Entrepreneur Relationship", paragraphs: ["When the Supporter chooses to support a specific Entrepreneur, the financial and participation relationship between that Supporter and Entrepreneur is governed by a separate Supporter–Entrepreneur Participation Agreement.", "EPEW is not a party to that separate agreement.", "The Entrepreneur remains responsible for obligations undertaken directly with the Supporter."] },
      { title: "4. Services Provided by EPEW", bullets: ["Supporter account access.", "Entrepreneur marketplace access.", "Entrepreneur qualification information.", "Support-unit selection tools.", "Payment-processing coordination.", "Payment and participation records.", "Supporter Financial Center access.", "Transaction history.", "Entrepreneur progress information.", "Communications and notifications.", "Reports and available business updates.", "Participation-benefit administration.", "Documentation and electronic recordkeeping.", "Customer and administrative support.", "Mediation and resolution assistance when appropriate."] },
      { title: "5. Entrepreneur Qualification", paragraphs: ["EPEW establishes qualification criteria and may review Entrepreneurs before allowing them to participate in the EPEW Marketplace.", "EPEW qualification means that an Entrepreneur has satisfied applicable EPEW eligibility and program requirements at the time of qualification.", "Qualification does not constitute a guarantee by EPEW that the Entrepreneur will become profitable, remain in business, fulfill every obligation, or produce any particular financial outcome."] },
      { title: "6. Supporter Responsibilities", bullets: ["Provide accurate account information.", "Maintain the confidentiality and security of login credentials.", "Review applicable agreements and disclosures before participating.", "Select participation voluntarily.", "Authorize payments only when participation is intended.", "Comply with applicable EPEW policies and procedures.", "Notify EPEW of material account or payment issues.", "Use EPEW services lawfully and responsibly."] },
      { title: "7. Payment Administration", paragraphs: ["EPEW may coordinate payment processing, recordkeeping, transaction tracking, and allocation of Supporter payments through approved payment processors and EPEW financial systems.", "The Supporter authorizes EPEW and its authorized payment processors to process payments according to the payment option selected by the Supporter.", "The specific amount, frequency, units, and applicable participation-benefit terms related to an Entrepreneur are governed by the Supporter–Entrepreneur Participation Agreement and the selected payment arrangement."] },
      { title: "8. Participation Benefits", paragraphs: ["Certain participation arrangements may provide an opportunity for participation benefits according to applicable EPEW policies, the Supporter–Entrepreneur Participation Agreement, business performance, and other applicable conditions.", "Weekly or Monthly Participation: up to 6% annually.", "Annual One-Time Participation: up to 8% annually.", "Participation benefits are not guaranteed."] },
      { title: "9. EPEW Mediation and Resolution Assistance", paragraphs: ["If a circumstance arises between a Supporter and an Entrepreneur concerning an obligation, payment, participation benefit, business performance, or another matter relating to their participation agreement, the Supporter may request EPEW assistance.", "EPEW may review available records, facilitate communication, obtain relevant information, assist the parties in identifying possible solutions, provide administrative mediation, and coordinate an appropriate resolution process under applicable EPEW policies.", "EPEW’s mediation role does not make EPEW responsible for the Entrepreneur’s obligations."] },
      { title: "10. No EPEW Responsibility for Entrepreneur Restitution", paragraphs: ["EPEW is not responsible for restitution, repayment, reimbursement, compensation, or satisfaction of a financial or contractual obligation owed by an Entrepreneur to a Supporter.", "If an Entrepreneur is unable to fulfill an obligation, EPEW will make reasonable efforts to assist the Entrepreneur and Supporter through communication, mediation, business-development assistance, and available ecosystem resources.", "The obligation remains the responsibility of the Entrepreneur unless a separate written agreement expressly provides otherwise."] },
      { title: "11. EPEW Entrepreneur-Success Support", paragraphs: ["EPEW intends to actively assist participating Entrepreneurs through available business coaching, enterprise-development services, business planning, operational coordination, marketing preparation, marketplace participation, business monitoring, reporting systems, professional-service coordination, technology, administrative support, and growth resources.", "EPEW’s purpose is not simply to process Supporter payments. EPEW works to improve the Entrepreneur’s opportunity to establish, operate, strengthen, and grow a sustainable business."] },
      { title: "12. Economic Growth Mission", paragraphs: ["EPEW also works to help Entrepreneurs and Supporters strengthen their financial position, increase economic opportunity, build stronger businesses and communities, and pursue long-term wealth growth through entrepreneurship, participation, collaboration, and responsible economic activity.", "EPEW does not guarantee any specific amount of wealth growth, income, participation benefit, business profitability, or financial outcome."] },
      { title: "13. Nature of EPEW", paragraphs: ["EPEW (EKERO Partners Empower Wealth LLC) operates as an entrepreneurship-development and community-participation platform.", "EPEW is not acting as the Supporter’s bank, lender, broker-dealer, investment adviser, financial adviser, securities exchange, or guarantor of Entrepreneur performance."] },
      { title: "14. Supporter Financial Records", paragraphs: ["EPEW may maintain electronic records regarding Supporter identity, supported businesses, selected units, payment frequency, payment amounts, transaction dates, payment status, participation agreements, participation benefits, applicable maturity or eligibility dates, distributions or returns when applicable, communications, and administrative activity."] },
      { title: "15. Communications", paragraphs: ["The Supporter authorizes EPEW to provide program-related communications through approved communication channels, including email, SMS, telephone, WhatsApp, dashboard notifications, or other authorized channels.", "Supporters remain responsible for maintaining accurate contact information."] },
      { title: "16. Electronic Agreements and Records", paragraphs: ["The Supporter agrees that electronic acceptance, checkboxes, electronic signatures, authenticated account actions, payment authorization, and other electronic records may serve as evidence of the Supporter’s consent and participation.", "EPEW may retain the applicable Supporter ID, agreement version, acceptance date and time, selected business, selected units, payment frequency, and related transaction information."] },
      { title: "17. Platform Access", paragraphs: ["EPEW may temporarily restrict or suspend platform access when reasonably necessary because of fraud concerns, account-security issues, violations of EPEW policies, payment disputes, misuse of the platform, legal requirements, or material compliance concerns.", "Such action does not automatically eliminate obligations already created under a separate Supporter–Entrepreneur Participation Agreement."] },
      { title: "18. Limitation of EPEW Responsibility", paragraphs: ["EPEW remains responsible for performing the platform and administrative responsibilities expressly undertaken by EPEW.", "EPEW does not assume responsibility for an Entrepreneur’s independent business decisions, business losses, failure to perform, restitution obligations, market conditions, third-party actions outside EPEW’s reasonable control, guaranteed participation benefits, or guaranteed financial growth.", "Nothing in this section is intended to eliminate responsibility that EPEW itself expressly undertakes under this Agreement or that cannot lawfully be excluded."] },
      { title: "19. Governing Law", paragraphs: ["This Agreement shall be governed by the applicable laws of the State of New York, except where another applicable law is required."] },
      { title: "20. Entire Agreement", paragraphs: ["This Agreement, together with applicable EPEW policies, disclosures, and electronically accepted program terms, constitutes the agreement governing the Supporter’s relationship with EPEW.", "The separate Supporter–Entrepreneur Participation Agreement governs the Supporter’s relationship with each supported Entrepreneur."] },
      { title: "21. Acceptance", paragraphs: ["By electronically accepting this Agreement, the Supporter confirms that the Supporter has reviewed the Agreement, understands the distinction between EPEW and the Entrepreneur, understands EPEW’s platform, administrative, and mediation roles, understands that EPEW does not assume the Entrepreneur’s restitution or repayment obligations, understands that participation benefits and financial outcomes are not guaranteed, and voluntarily agrees to participate subject to these terms."] }
    ],
    checkboxText: "I have read and agree to the EPEW Supporter Platform Participation Agreement with EPEW (EKERO Partners Empower Wealth LLC). I understand EPEW’s platform, administrative, and mediation role and understand that EPEW does not assume an Entrepreneur’s restitution, repayment, or other contractual obligations.",
    acceptanceError: "Please read and accept the EPEW Supporter Platform Participation Agreement before continuing.",
    acceptanceServerError: "Unable to record your agreement acceptance.",
    returnButton: "Return to Support Transaction",
    acceptReturnButton: "Accept and Return to Support Transaction",
    acceptContinueButton: "Accept and Continue"
  },
  fr: {
    eyebrow: "Convention du Supporteur EPEW",
    title: "Convention de participation du Supporteur à la plateforme EPEW",
    subtitle: "Entre le Supporteur et EPEW (EKERO Partners Empower Wealth LLC)",
    sections: [
      { title: "1. Parties", paragraphs: ["La présente Convention est conclue entre EPEW (EKERO Partners Empower Wealth LLC), désignée « EPEW », et la personne inscrite sur la plateforme EPEW comme Supporteur, désignée « Supporteur ».", "Elle régit la relation entre EPEW et le Supporteur concernant l’utilisation de la plateforme EPEW et la participation à l’écosystème de développement entrepreneurial EPEW."] },
      { title: "2. Objet", paragraphs: ["EPEW exploite un écosystème de développement entrepreneurial et de soutien communautaire qui met en relation des entrepreneurs qualifiés avec des supporteurs et fournit la technologie, l’administration, l’infrastructure de développement des entreprises, les systèmes de communication, l’administration financière et d’autres services nécessaires.", "Le Supporteur choisit volontairement de participer à l’écosystème EPEW sous réserve de la présente Convention et des politiques et procédures applicables d’EPEW."] },
      { title: "3. Relation distincte Supporteur–Entrepreneur", paragraphs: ["Lorsqu’un Supporteur choisit de soutenir un Entrepreneur déterminé, leur relation financière et de participation est régie par une Convention distincte de participation Supporteur–Entrepreneur.", "EPEW n’est pas partie à cette Convention distincte.", "L’Entrepreneur demeure responsable des obligations qu’il assume directement envers le Supporteur."] },
      { title: "4. Services fournis par EPEW", bullets: ["Accès au compte Supporteur.", "Accès au marché des entrepreneurs.", "Informations de qualification des entrepreneurs.", "Outils de sélection des unités de soutien.", "Coordination du traitement des paiements.", "Dossiers de paiement et de participation.", "Accès au Centre financier du Supporteur.", "Historique des transactions.", "Informations sur la progression de l’Entrepreneur.", "Communications et notifications.", "Rapports et mises à jour disponibles sur l’entreprise.", "Administration des avantages de participation.", "Documentation et tenue de dossiers électroniques.", "Soutien à la clientèle et administratif.", "Aide à la médiation et à la résolution lorsque cela est approprié."] },
      { title: "5. Qualification de l’Entrepreneur", paragraphs: ["EPEW établit des critères de qualification et peut examiner les Entrepreneurs avant de leur permettre de participer au Marché EPEW.", "La qualification EPEW signifie que l’Entrepreneur a satisfait aux exigences d’admissibilité et de programme applicables au moment de la qualification.", "La qualification ne garantit pas que l’Entrepreneur sera rentable, restera en activité, remplira toutes ses obligations ou produira un résultat financier particulier."] },
      { title: "6. Responsabilités du Supporteur", bullets: ["Fournir des renseignements de compte exacts.", "Protéger les identifiants de connexion.", "Examiner les conventions et divulgations applicables avant de participer.", "Choisir volontairement sa participation.", "Autoriser les paiements uniquement lorsqu’il souhaite participer.", "Respecter les politiques et procédures EPEW applicables.", "Informer EPEW des problèmes importants de compte ou de paiement.", "Utiliser les services EPEW légalement et de façon responsable."] },
      { title: "7. Administration des paiements", paragraphs: ["EPEW peut coordonner le traitement des paiements, la tenue des dossiers, le suivi des transactions et l’allocation des paiements par des processeurs approuvés et les systèmes financiers EPEW.", "Le Supporteur autorise EPEW et ses processeurs de paiement autorisés à traiter les paiements selon l’option choisie.", "Le montant, la fréquence, les unités et les conditions d’avantage de participation liés à un Entrepreneur sont régis par la Convention Supporteur–Entrepreneur et l’arrangement de paiement choisi."] },
      { title: "8. Avantages de participation", paragraphs: ["Certaines modalités peuvent offrir une possibilité d’avantages de participation selon les politiques EPEW, la Convention Supporteur–Entrepreneur, la performance de l’entreprise et d’autres conditions applicables.", "Participation hebdomadaire ou mensuelle : jusqu’à 6 % par année.", "Participation annuelle en un seul paiement : jusqu’à 8 % par année.", "Les avantages de participation ne sont pas garantis."] },
      { title: "9. Médiation et aide à la résolution par EPEW", paragraphs: ["Si une situation survient entre un Supporteur et un Entrepreneur concernant une obligation, un paiement, un avantage de participation, la performance de l’entreprise ou un autre sujet lié à leur Convention, le Supporteur peut demander l’aide d’EPEW.", "EPEW peut examiner les dossiers disponibles, faciliter la communication, obtenir des informations pertinentes, aider à identifier des solutions possibles, assurer une médiation administrative et coordonner un processus de résolution approprié.", "Le rôle de médiation d’EPEW ne rend pas EPEW responsable des obligations de l’Entrepreneur."] },
      { title: "10. Aucune responsabilité d’EPEW pour la restitution de l’Entrepreneur", paragraphs: ["EPEW n’est pas responsable d’une restitution, d’un remboursement, d’une indemnisation ou de l’exécution d’une obligation financière ou contractuelle due par un Entrepreneur à un Supporteur.", "Si un Entrepreneur ne peut remplir une obligation, EPEW fera des efforts raisonnables pour aider les parties par la communication, la médiation, l’aide au développement de l’entreprise et les ressources disponibles de l’écosystème.", "L’obligation demeure celle de l’Entrepreneur sauf disposition expresse contraire dans un accord écrit distinct."] },
      { title: "11. Soutien d’EPEW à la réussite entrepreneuriale", paragraphs: ["EPEW entend aider activement les Entrepreneurs participants par le coaching, les services de développement d’entreprise, la planification, la coordination opérationnelle, la préparation marketing, le marché, le suivi, les rapports, la coordination de services professionnels, la technologie, le soutien administratif et les ressources de croissance disponibles.", "EPEW ne se limite pas au traitement des paiements; EPEW cherche à améliorer les chances de l’Entrepreneur d’établir, exploiter, renforcer et développer une entreprise durable."] },
      { title: "12. Mission de croissance économique", paragraphs: ["EPEW œuvre aussi à aider Entrepreneurs et Supporteurs à renforcer leur situation financière, accroître les possibilités économiques, bâtir des entreprises et communautés plus fortes et poursuivre une croissance patrimoniale à long terme par l’entrepreneuriat, la participation, la collaboration et une activité économique responsable.", "EPEW ne garantit aucun montant précis de croissance patrimoniale, revenu, avantage de participation, rentabilité ou résultat financier."] },
      { title: "13. Nature d’EPEW", paragraphs: ["EPEW (EKERO Partners Empower Wealth LLC) fonctionne comme une plateforme de développement entrepreneurial et de participation communautaire.", "EPEW n’agit pas comme banque, prêteur, courtier en valeurs mobilières, conseiller en placement, conseiller financier, bourse de valeurs ou garant de la performance de l’Entrepreneur pour le Supporteur."] },
      { title: "14. Dossiers financiers du Supporteur", paragraphs: ["EPEW peut conserver des dossiers électroniques concernant l’identité du Supporteur, les entreprises soutenues, les unités choisies, la fréquence et les montants des paiements, les dates et statuts des transactions, les conventions, les avantages, les dates d’admissibilité, les distributions ou retours le cas échéant, les communications et l’activité administrative."] },
      { title: "15. Communications", paragraphs: ["Le Supporteur autorise EPEW à transmettre des communications liées au programme par les canaux approuvés, notamment courriel, SMS, téléphone, WhatsApp, notifications du tableau de bord ou autres canaux autorisés.", "Le Supporteur demeure responsable de maintenir des coordonnées exactes."] },
      { title: "16. Conventions et dossiers électroniques", paragraphs: ["Le Supporteur accepte que l’acceptation électronique, les cases à cocher, signatures électroniques, actions de compte authentifiées, autorisations de paiement et autres dossiers électroniques puissent servir de preuve de son consentement et de sa participation.", "EPEW peut conserver l’identifiant du Supporteur, la version de la Convention, la date et l’heure d’acceptation, l’entreprise choisie, les unités, la fréquence de paiement et les informations de transaction liées."] },
      { title: "17. Accès à la plateforme", paragraphs: ["EPEW peut temporairement restreindre ou suspendre l’accès lorsque cela est raisonnablement nécessaire pour des préoccupations de fraude, de sécurité, des violations de politiques, des litiges de paiement, un mauvais usage, des exigences légales ou des préoccupations importantes de conformité.", "Une telle mesure n’élimine pas automatiquement les obligations déjà créées par une Convention Supporteur–Entrepreneur distincte."] },
      { title: "18. Limitation de la responsabilité d’EPEW", paragraphs: ["EPEW demeure responsable des fonctions de plateforme et d’administration qu’elle assume expressément.", "EPEW n’assume pas la responsabilité des décisions commerciales indépendantes de l’Entrepreneur, pertes commerciales, défauts d’exécution, obligations de restitution, conditions du marché, actes de tiers hors de son contrôle raisonnable, avantages garantis ou croissance financière garantie.", "Aucune disposition de cette section ne vise à éliminer une responsabilité qu’EPEW assume expressément ou qui ne peut légalement être exclue."] },
      { title: "19. Droit applicable", paragraphs: ["La présente Convention est régie par les lois applicables de l’État de New York, sauf lorsqu’une autre loi applicable est requise."] },
      { title: "20. Intégralité de la Convention", paragraphs: ["La présente Convention, avec les politiques, divulgations et modalités de programme acceptées électroniquement, constitue l’accord régissant la relation du Supporteur avec EPEW.", "La Convention Supporteur–Entrepreneur distincte régit la relation du Supporteur avec chaque Entrepreneur soutenu."] },
      { title: "21. Acceptation", paragraphs: ["En acceptant électroniquement, le Supporteur confirme avoir examiné la Convention, comprendre la distinction entre EPEW et l’Entrepreneur, les rôles de plateforme, d’administration et de médiation d’EPEW, que EPEW n’assume pas les obligations de restitution ou de remboursement de l’Entrepreneur, que les avantages et résultats financiers ne sont pas garantis, et accepte volontairement de participer selon ces conditions."] }
    ],
    checkboxText: "J’ai lu et j’accepte la Convention de participation du Supporteur à la plateforme EPEW avec EPEW (EKERO Partners Empower Wealth LLC). Je comprends le rôle de plateforme, d’administration et de médiation d’EPEW et que EPEW n’assume pas les obligations de restitution, remboursement ou autres obligations contractuelles d’un Entrepreneur.",
    acceptanceError: "Veuillez lire et accepter la Convention de participation du Supporteur à la plateforme EPEW avant de continuer.",
    acceptanceServerError: "Impossible d’enregistrer votre acceptation de la Convention.",
    returnButton: "Retour à la transaction de soutien",
    acceptReturnButton: "Accepter et retourner à la transaction de soutien",
    acceptContinueButton: "Accepter et continuer"
  },
  es: {
    eyebrow: "Acuerdo del Colaborador EPEW",
    title: "Acuerdo de Participación del Colaborador en la Plataforma EPEW",
    subtitle: "Entre el Colaborador y EPEW (EKERO Partners Empower Wealth LLC)",
    sections: [
      { title: "1. Partes", paragraphs: ["Este Acuerdo se celebra entre EPEW (EKERO Partners Empower Wealth LLC), denominada “EPEW”, y la persona registrada en la plataforma EPEW como Colaborador, denominada “Colaborador”.", "Este Acuerdo rige la relación entre EPEW y el Colaborador respecto al uso de la plataforma EPEW y la participación en el Ecosistema de Desarrollo Empresarial EPEW."] },
      { title: "2. Propósito", paragraphs: ["EPEW opera un ecosistema de desarrollo empresarial y apoyo comunitario diseñado para conectar emprendedores calificados con colaboradores y proporcionar tecnología, administración, infraestructura de desarrollo empresarial, sistemas de comunicación, administración financiera y otros servicios necesarios.", "El Colaborador elige voluntariamente participar en el ecosistema EPEW sujeto a este Acuerdo y a las políticas y procedimientos aplicables de EPEW."] },
      { title: "3. Relación separada Colaborador–Emprendedor", paragraphs: ["Cuando el Colaborador decide apoyar a un Emprendedor específico, la relación financiera y de participación entre ambos se rige por un Acuerdo de Participación Colaborador–Emprendedor separado.", "EPEW no es parte de ese acuerdo separado.", "El Emprendedor sigue siendo responsable de las obligaciones asumidas directamente con el Colaborador."] },
      { title: "4. Servicios proporcionados por EPEW", bullets: ["Acceso a la cuenta del Colaborador.", "Acceso al mercado de emprendedores.", "Información de calificación de emprendedores.", "Herramientas de selección de unidades de apoyo.", "Coordinación del procesamiento de pagos.", "Registros de pago y participación.", "Acceso al Centro Financiero del Colaborador.", "Historial de transacciones.", "Información sobre el progreso del Emprendedor.", "Comunicaciones y notificaciones.", "Informes y actualizaciones comerciales disponibles.", "Administración de beneficios de participación.", "Documentación y registros electrónicos.", "Atención al cliente y apoyo administrativo.", "Asistencia de mediación y resolución cuando corresponda."] },
      { title: "5. Calificación del Emprendedor", paragraphs: ["EPEW establece criterios de calificación y puede revisar a los Emprendedores antes de permitirles participar en el Mercado EPEW.", "La calificación EPEW significa que un Emprendedor cumplió los requisitos aplicables de elegibilidad y del programa al momento de la calificación.", "La calificación no garantiza que el Emprendedor será rentable, continuará operando, cumplirá todas sus obligaciones ni producirá un resultado financiero determinado."] },
      { title: "6. Responsabilidades del Colaborador", bullets: ["Proporcionar información correcta de la cuenta.", "Mantener la confidencialidad y seguridad de las credenciales.", "Revisar los acuerdos y divulgaciones aplicables antes de participar.", "Seleccionar la participación voluntariamente.", "Autorizar pagos únicamente cuando tenga intención de participar.", "Cumplir con las políticas y procedimientos aplicables de EPEW.", "Notificar a EPEW sobre problemas importantes de cuenta o pago.", "Utilizar los servicios de EPEW de forma legal y responsable."] },
      { title: "7. Administración de pagos", paragraphs: ["EPEW puede coordinar el procesamiento de pagos, registros, seguimiento de transacciones y asignación de pagos mediante procesadores aprobados y sistemas financieros EPEW.", "El Colaborador autoriza a EPEW y a sus procesadores autorizados a procesar pagos según la opción seleccionada.", "El monto, frecuencia, unidades y condiciones del beneficio de participación relacionados con un Emprendedor se rigen por el Acuerdo Colaborador–Emprendedor y la modalidad de pago seleccionada."] },
      { title: "8. Beneficios de participación", paragraphs: ["Ciertas modalidades pueden ofrecer la oportunidad de beneficios de participación según las políticas aplicables de EPEW, el Acuerdo Colaborador–Emprendedor, el desempeño del negocio y otras condiciones.", "Participación semanal o mensual: hasta 6% anual.", "Participación anual en un solo pago: hasta 8% anual.", "Los beneficios de participación no están garantizados."] },
      { title: "9. Mediación y asistencia de resolución de EPEW", paragraphs: ["Si surge una situación entre un Colaborador y un Emprendedor relacionada con una obligación, pago, beneficio, desempeño comercial u otro asunto de su acuerdo, el Colaborador puede solicitar asistencia de EPEW.", "EPEW puede revisar registros disponibles, facilitar la comunicación, obtener información pertinente, ayudar a identificar soluciones, proporcionar mediación administrativa y coordinar un proceso apropiado de resolución.", "El papel de mediación de EPEW no hace responsable a EPEW por las obligaciones del Emprendedor."] },
      { title: "10. EPEW no es responsable de la restitución del Emprendedor", paragraphs: ["EPEW no es responsable de restitución, reembolso, compensación ni cumplimiento de una obligación financiera o contractual que un Emprendedor deba a un Colaborador.", "Si un Emprendedor no puede cumplir una obligación, EPEW hará esfuerzos razonables para ayudar mediante comunicación, mediación, asistencia de desarrollo empresarial y recursos disponibles del ecosistema.", "La obligación sigue siendo responsabilidad del Emprendedor salvo que un acuerdo escrito separado disponga expresamente lo contrario."] },
      { title: "11. Apoyo de EPEW al éxito del Emprendedor", paragraphs: ["EPEW busca ayudar activamente a los Emprendedores mediante coaching, desarrollo empresarial, planificación, coordinación operativa, preparación de marketing, participación en el mercado, seguimiento, sistemas de informes, coordinación de servicios profesionales, tecnología, apoyo administrativo y recursos de crecimiento disponibles.", "El propósito de EPEW no es simplemente procesar pagos; EPEW trabaja para mejorar la oportunidad del Emprendedor de establecer, operar, fortalecer y hacer crecer un negocio sostenible."] },
      { title: "12. Misión de crecimiento económico", paragraphs: ["EPEW también trabaja para ayudar a Emprendedores y Colaboradores a fortalecer su posición financiera, aumentar oportunidades económicas, construir negocios y comunidades más fuertes y buscar crecimiento patrimonial a largo plazo mediante emprendimiento, participación, colaboración y actividad económica responsable.", "EPEW no garantiza ninguna cantidad específica de crecimiento patrimonial, ingresos, beneficio de participación, rentabilidad o resultado financiero."] },
      { title: "13. Naturaleza de EPEW", paragraphs: ["EPEW (EKERO Partners Empower Wealth LLC) opera como plataforma de desarrollo empresarial y participación comunitaria.", "EPEW no actúa como banco, prestamista, corredor de valores, asesor de inversiones, asesor financiero, bolsa de valores ni garante del desempeño del Emprendedor para el Colaborador."] },
      { title: "14. Registros financieros del Colaborador", paragraphs: ["EPEW puede mantener registros electrónicos sobre identidad del Colaborador, negocios apoyados, unidades seleccionadas, frecuencia y montos de pago, fechas y estado de transacciones, acuerdos, beneficios, fechas de elegibilidad, distribuciones o retornos cuando correspondan, comunicaciones y actividad administrativa."] },
      { title: "15. Comunicaciones", paragraphs: ["El Colaborador autoriza a EPEW a proporcionar comunicaciones relacionadas con el programa mediante canales aprobados, incluidos correo electrónico, SMS, teléfono, WhatsApp, notificaciones del panel u otros canales autorizados.", "El Colaborador sigue siendo responsable de mantener información de contacto correcta."] },
      { title: "16. Acuerdos y registros electrónicos", paragraphs: ["El Colaborador acepta que la aceptación electrónica, casillas, firmas electrónicas, acciones autenticadas de cuenta, autorizaciones de pago y otros registros electrónicos pueden servir como evidencia de su consentimiento y participación.", "EPEW puede conservar la identificación del Colaborador, versión del acuerdo, fecha y hora de aceptación, negocio seleccionado, unidades, frecuencia de pago e información relacionada con la transacción."] },
      { title: "17. Acceso a la plataforma", paragraphs: ["EPEW puede restringir o suspender temporalmente el acceso cuando sea razonablemente necesario por preocupaciones de fraude, seguridad de cuenta, violaciones de políticas, disputas de pago, uso indebido, requisitos legales o preocupaciones importantes de cumplimiento.", "Esta acción no elimina automáticamente obligaciones ya creadas bajo un Acuerdo Colaborador–Emprendedor separado."] },
      { title: "18. Limitación de responsabilidad de EPEW", paragraphs: ["EPEW sigue siendo responsable de las responsabilidades de plataforma y administración que asume expresamente.", "EPEW no asume responsabilidad por decisiones comerciales independientes del Emprendedor, pérdidas comerciales, incumplimiento, obligaciones de restitución, condiciones del mercado, acciones de terceros fuera de su control razonable, beneficios garantizados o crecimiento financiero garantizado.", "Nada en esta sección pretende eliminar una responsabilidad que EPEW asuma expresamente o que legalmente no pueda excluirse."] },
      { title: "19. Ley aplicable", paragraphs: ["Este Acuerdo se regirá por las leyes aplicables del Estado de Nueva York, salvo cuando otra ley aplicable sea obligatoria."] },
      { title: "20. Acuerdo completo", paragraphs: ["Este Acuerdo, junto con las políticas, divulgaciones y términos del programa aceptados electrónicamente, constituye el acuerdo que rige la relación del Colaborador con EPEW.", "El Acuerdo Colaborador–Emprendedor separado rige la relación del Colaborador con cada Emprendedor apoyado."] },
      { title: "21. Aceptación", paragraphs: ["Al aceptar electrónicamente este Acuerdo, el Colaborador confirma que lo ha revisado, comprende la diferencia entre EPEW y el Emprendedor, comprende los roles de plataforma, administración y mediación de EPEW, comprende que EPEW no asume las obligaciones de restitución o reembolso del Emprendedor, comprende que los beneficios y resultados financieros no están garantizados y acepta participar voluntariamente bajo estos términos."] }
    ],
    checkboxText: "He leído y acepto el Acuerdo de Participación del Colaborador en la Plataforma EPEW con EPEW (EKERO Partners Empower Wealth LLC). Comprendo el papel de plataforma, administración y mediación de EPEW y que EPEW no asume las obligaciones de restitución, reembolso u otras obligaciones contractuales de un Emprendedor.",
    acceptanceError: "Lea y acepte el Acuerdo de Participación del Colaborador en la Plataforma EPEW antes de continuar.",
    acceptanceServerError: "No se pudo registrar su aceptación del acuerdo.",
    returnButton: "Volver a la transacción de apoyo",
    acceptReturnButton: "Aceptar y volver a la transacción de apoyo",
    acceptContinueButton: "Aceptar y continuar"
  },
  ht: {
    eyebrow: "Akò Sipòtè EPEW",
    title: "Akò Patisipasyon Sipòtè sou Platfòm EPEW",
    subtitle: "Ant Sipòtè a ak EPEW (EKERO Partners Empower Wealth LLC)",
    sections: [
      { title: "1. Pati yo", paragraphs: ["Akò sa a fèt ant EPEW (EKERO Partners Empower Wealth LLC), yo rele “EPEW” nan Akò sa a, ak moun ki anrejistre sou platfòm EPEW kòm Sipòtè a.", "Akò sa a gouvène relasyon ant EPEW ak Sipòtè a konsènan itilizasyon platfòm EPEW ak patisipasyon nan Ekosistèm Devlopman Antreprenè EPEW la."] },
      { title: "2. Objektif", paragraphs: ["EPEW opere yon ekosistèm devlopman antreprenarya ak sipò kominotè ki konekte antreprenè kalifye ak sipòtè epi bay teknoloji, administrasyon, enfrastrikti devlopman biznis, sistèm kominikasyon, administrasyon finansye ak lòt sèvis ki nesesè.", "Sipòtè a chwazi volontèman patisipe nan ekosistèm EPEW la dapre Akò sa a ak politik ak pwosedi EPEW ki aplikab yo."] },
      { title: "3. Relasyon separe ant Sipòtè ak Antreprenè", paragraphs: ["Lè Sipòtè a chwazi sipòte yon Antreprenè espesifik, relasyon finansye ak patisipasyon ant yo gouvène pa yon Akò Patisipasyon Sipòtè–Antreprenè apa.", "EPEW pa yon pati nan akò separe sa a.", "Antreprenè a rete responsab pou obligasyon li pran dirèkteman anvè Sipòtè a."] },
      { title: "4. Sèvis EPEW bay", bullets: ["Aksè nan kont Sipòtè.", "Aksè nan mache antreprenè yo.", "Enfòmasyon sou kalifikasyon antreprenè.", "Zouti pou chwazi Inite Sipò.", "Kowòdinasyon tretman peman.", "Dosye peman ak patisipasyon.", "Aksè nan Sant Finansye Sipòtè.", "Istwa tranzaksyon.", "Enfòmasyon sou pwogrè Antreprenè.", "Kominikasyon ak notifikasyon.", "Rapò ak mizajou biznis ki disponib.", "Administrasyon benefis patisipasyon.", "Dokimantasyon ak dosye elektwonik.", "Sipò kliyan ak administratif.", "Èd medyasyon ak rezolisyon lè sa apwopriye."] },
      { title: "5. Kalifikasyon Antreprenè", paragraphs: ["EPEW etabli kritè kalifikasyon epi li ka revize Antreprenè yo anvan li pèmèt yo patisipe nan Mache EPEW la.", "Kalifikasyon EPEW vle di yon Antreprenè satisfè kondisyon kalifikasyon ak pwogram ki aplikab yo nan moman kalifikasyon an.", "Kalifikasyon an pa yon garanti Antreprenè a ap fè pwofi, ap rete nan biznis, ap respekte tout obligasyon oswa ap bay yon rezilta finansye espesifik."] },
      { title: "6. Responsablite Sipòtè a", bullets: ["Bay enfòmasyon kont ki kòrèk.", "Pwoteje enfòmasyon koneksyon yo.", "Revize akò ak divilgasyon ki aplikab yo anvan patisipasyon.", "Chwazi patisipasyon volontèman.", "Otorize peman sèlman lè li vle patisipe.", "Respekte politik ak pwosedi EPEW ki aplikab yo.", "Avèti EPEW sou pwoblèm enpòtan kont oswa peman.", "Itilize sèvis EPEW legalman ak responsab."] },
      { title: "7. Administrasyon Peman", paragraphs: ["EPEW ka kowòdone tretman peman, kenbe dosye, swiv tranzaksyon ak alokasyon peman Sipòtè atravè processeur apwouve ak sistèm finansye EPEW.", "Sipòtè a otorize EPEW ak processeur peman otorize li yo pou trete peman dapre opsyon Sipòtè a chwazi a.", "Kantite lajan, frekans, inite ak kondisyon benefis patisipasyon ki gen rapò ak yon Antreprenè gouvène pa Akò Sipòtè–Antreprenè ak aranjman peman yo chwazi a."] },
      { title: "8. Benefis Patisipasyon", paragraphs: ["Kèk aranjman patisipasyon ka bay opòtinite pou benefis patisipasyon dapre politik EPEW ki aplikab yo, Akò Sipòtè–Antreprenè, pèfòmans biznis ak lòt kondisyon.", "Patisipasyon chak semèn oswa chak mwa: jiska 6% pa ane.", "Patisipasyon anyèl yon sèl peman: jiska 8% pa ane.", "Benefis patisipasyon yo pa garanti."] },
      { title: "9. Medyasyon ak Èd Rezolisyon EPEW", paragraphs: ["Si gen yon sitiyasyon ant Sipòtè a ak Antreprenè a sou yon obligasyon, peman, benefis, pèfòmans biznis oswa lòt kesyon ki gen rapò ak akò yo, Sipòtè a ka mande EPEW èd.", "EPEW ka revize dosye ki disponib, fasilite kominikasyon, jwenn enfòmasyon enpòtan, ede idantifye solisyon, bay medyasyon administratif epi kowòdone yon pwosesis rezolisyon apwopriye.", "Wòl medyasyon EPEW la pa fè EPEW responsab pou obligasyon Antreprenè a."] },
      { title: "10. EPEW pa responsab pou restitisyon Antreprenè a", paragraphs: ["EPEW pa responsab pou restitisyon, ranbousman, konpansasyon oswa satisfaksyon yon obligasyon finansye oswa kontra Antreprenè a dwe Sipòtè a.", "Si Antreprenè a pa ka ranpli yon obligasyon, EPEW ap fè efò rezonab pou ede atravè kominikasyon, medyasyon, asistans devlopman biznis ak resous ekosistèm ki disponib.", "Obligasyon an rete responsablite Antreprenè a sof si yon lòt akò ekri di klèman otreman."] },
      { title: "11. Sipò EPEW pou Siksè Antreprenè", paragraphs: ["EPEW gen entansyon ede Antreprenè k ap patisipe yo aktivman atravè coaching biznis, sèvis devlopman antrepriz, planifikasyon, kowòdinasyon operasyon, preparasyon maketing, patisipasyon nan mache, siveyans, sistèm rapò, kowòdinasyon sèvis pwofesyonèl, teknoloji, sipò administratif ak resous kwasans ki disponib.", "Objektif EPEW pa sèlman trete peman Sipòtè. EPEW travay pou amelyore chans Antreprenè a pou etabli, opere, ranfòse ak grandi yon biznis dirab."] },
      { title: "12. Misyon Kwasans Ekonomik", paragraphs: ["EPEW travay tou pou ede Antreprenè ak Sipòtè ranfòse pozisyon finansye yo, ogmante opòtinite ekonomik, bati biznis ak kominote pi solid, epi pouswiv kwasans richès alontèm atravè antreprenarya, patisipasyon, kolaborasyon ak aktivite ekonomik responsab.", "EPEW pa garanti okenn kantite espesifik kwasans richès, revni, benefis patisipasyon, rentabilite biznis oswa rezilta finansye."] },
      { title: "13. Nati EPEW", paragraphs: ["EPEW (EKERO Partners Empower Wealth LLC) opere kòm yon platfòm devlopman antreprenarya ak patisipasyon kominotè.", "EPEW pa aji kòm bank, kreditè, koutye-vandè, konseye envestisman, konseye finansye, echanj sekirite oswa garanti pèfòmans Antreprenè pou Sipòtè a."] },
      { title: "14. Dosye Finansye Sipòtè", paragraphs: ["EPEW ka kenbe dosye elektwonik sou idantite Sipòtè, biznis yo sipòte, inite yo chwazi, frekans ak kantite peman, dat ak estati tranzaksyon, akò patisipasyon, benefis, dat kalifikasyon, distribisyon oswa retou lè sa aplikab, kominikasyon ak aktivite administratif."] },
      { title: "15. Kominikasyon", paragraphs: ["Sipòtè a otorize EPEW pou bay kominikasyon ki gen rapò ak pwogram nan atravè chanèl apwouve tankou imel, SMS, telefòn, WhatsApp, notifikasyon tablodbò oswa lòt chanèl otorize.", "Sipòtè yo rete responsab pou kenbe enfòmasyon kontak yo kòrèk."] },
      { title: "16. Akò ak Dosye Elektwonik", paragraphs: ["Sipòtè a dakò akseptasyon elektwonik, bwat seleksyon, siyati elektwonik, aksyon kont otantifye, otorizasyon peman ak lòt dosye elektwonik ka sèvi kòm prèv konsantman ak patisipasyon li.", "EPEW ka konsève ID Sipòtè a, vèsyon akò a, dat ak lè akseptasyon, biznis yo chwazi a, inite yo, frekans peman ak enfòmasyon tranzaksyon ki gen rapò."] },
      { title: "17. Aksè Platfòm", paragraphs: ["EPEW ka tanporèman limite oswa sispann aksè lè sa rezonabman nesesè akòz enkyetid fwod, sekirite kont, vyolasyon politik, diskisyon peman, move itilizasyon, kondisyon legal oswa gwo enkyetid konfòmite.", "Aksyon sa a pa otomatikman elimine obligasyon ki deja kreye anba yon Akò Sipòtè–Antreprenè apa."] },
      { title: "18. Limit Responsablite EPEW", paragraphs: ["EPEW rete responsab pou responsablite platfòm ak administratif li pran klèman.", "EPEW pa pran responsablite pou desizyon biznis endepandan Antreprenè a, pèt biznis, echèk pou egzekite, obligasyon restitisyon, kondisyon mache, aksyon twazyèm pati andeyò kontwòl rezonab EPEW, benefis patisipasyon garanti oswa kwasans finansye garanti.", "Pa gen anyen nan seksyon sa a ki fèt pou elimine yon responsablite EPEW pran klèman oswa yon responsablite lalwa pa pèmèt yo eskli."] },
      { title: "19. Lwa ki Aplikab", paragraphs: ["Akò sa a ap gouvène dapre lwa ki aplikab nan Eta New York, sof kote yon lòt lwa aplikab obligatwa."] },
      { title: "20. Akò Konplè", paragraphs: ["Akò sa a, ansanm ak politik EPEW, divilgasyon ak kondisyon pwogram yo aksepte elektwonikman, fòme akò ki gouvène relasyon Sipòtè a ak EPEW.", "Akò Sipòtè–Antreprenè apa a gouvène relasyon Sipòtè a ak chak Antreprenè li sipòte."] },
      { title: "21. Akseptasyon", paragraphs: ["Lè Sipòtè a aksepte Akò sa a elektwonikman, li konfime li revize Akò a, li konprann diferans ant EPEW ak Antreprenè a, wòl platfòm, administratif ak medyasyon EPEW, li konprann EPEW pa pran obligasyon restitisyon oswa ranbousman Antreprenè a, li konprann benefis ak rezilta finansye yo pa garanti, epi li dakò volontèman patisipe dapre kondisyon sa yo."] }
    ],
    checkboxText: "Mwen li epi mwen dakò ak Akò Patisipasyon Sipòtè sou Platfòm EPEW avèk EPEW (EKERO Partners Empower Wealth LLC). Mwen konprann wòl platfòm, administratif ak medyasyon EPEW epi mwen konprann EPEW pa pran obligasyon restitisyon, ranbousman oswa lòt obligasyon kontra yon Antreprenè.",
    acceptanceError: "Tanpri li epi aksepte Akò Patisipasyon Sipòtè sou Platfòm EPEW anvan ou kontinye.",
    acceptanceServerError: "Nou pa t kapab anrejistre akseptasyon akò ou a.",
    returnButton: "Retounen nan tranzaksyon sipò a",
    acceptReturnButton: "Aksepte epi retounen nan tranzaksyon sipò a",
    acceptContinueButton: "Aksepte epi kontinye"
  }
};

export function getSupporterEntrepreneurAgreementCopy(locale: SupportedLocale) {
  return supporterEntrepreneur[locale] ?? supporterEntrepreneur.en;
}

export function getSupporterEpewAgreementCopy(locale: SupportedLocale) {
  return supporterEpew[locale] ?? supporterEpew.en;
}
