"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
export default function Messages(){
 const [conversations,setConversations]=useState<any[]>([]),[drafts,setDrafts]=useState<Record<string,string>>({}),[status,setStatus]=useState("Loading conversations…");
 async function load(){const r=await fetch("/api/entrepreneurs/coach-messages");if(r.status===401){window.location.assign("/entrepreneurs/login");return;}if(!r.ok){setStatus("Unable to load your coach conversations.");return;}setConversations((await r.json()).conversations);setStatus("");}
 useEffect(()=>{void load();},[]);
 async function send(id:string){const r=await fetch("/api/entrepreneurs/coach-messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assignment:id,body:drafts[id]})});if(r.ok){setDrafts(x=>({...x,[id]:""}));await load();setStatus("Message sent to your assigned coach.");}else setStatus("Unable to send. Check your current coach assignment.");}
 return <main className="min-h-screen bg-slate-50 p-8 text-[#06245c]"><nav className="mb-8 flex justify-between"><a href="/entrepreneurs/dashboard" className="font-bold">Entrepreneur Dashboard</a><button onClick={async()=>{await supabase.auth.signOut();window.location.assign("/entrepreneurs/login");}}>Sign out</button></nav><h1 className="text-3xl font-bold">Coach Communications</h1><p className="my-4">Send and receive messages with your assigned EPEW coach.</p>{!conversations.length&&!status&&<p>No current coach assignment. Contact EPEW for assistance.</p>}{conversations.map(c=><section key={c.assignment_id} className="my-6 rounded-xl bg-white p-6 shadow"><h2 className="text-2xl font-bold">{c.coach?.name??"Assigned coach"} · Application {c.application_id}</h2><p>{c.coach?.email}</p><div className="my-6 space-y-3">{!c.messages.length&&<p>No messages yet. You can send your coach a message below.</p>}{c.messages.map((m:any)=><article key={m.id} className="rounded border p-4"><p className="text-sm text-slate-600">{new Date(m.created_at).toLocaleString()}</p><p className="whitespace-pre-wrap">{m.body}</p>{m.kind==="document"&&<button className="underline" onClick={async()=>{const r=await fetch(`/api/entrepreneurs/coach-messages?document=${encodeURIComponent(m.id)}`);if(r.ok)window.open((await r.json()).url,"_blank","noopener,noreferrer");else setStatus("Document access unavailable.");}}>Download document</button>}</article>)}</div><form onSubmit={e=>{e.preventDefault();void send(c.assignment_id);}}><label className="block">Your message<textarea value={drafts[c.assignment_id]??""} onChange={e=>setDrafts(x=>({...x,[c.assignment_id]:e.target.value}))} required maxLength={10000} className="my-3 block w-full rounded border p-3"/></label><button className="rounded bg-green-800 p-3 text-white">Send to coach</button></form></section>)}<p role="status">{status}</p></main>;
}
